namespace AllInOne.Legal.Domain.Master
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping template
    /// </summary>
    [Serializable]
    public class AuthorizeURLViewEntity
    {
        #region Properties

        /// <summary>
        /// Gets or sets the RanaGrpObsInd field.
        /// </summary>
        public System.String RanaGrpObsInd
        {
            get;
             			set;
        }

        /// <summary>
        /// Gets or sets the RoleCode field.
        /// </summary>
        public System.String RoleCode
        {
            get;
             			set;
        }

        /// <summary>
        /// Gets or sets the RUserOrgRleObsInd field.
        /// </summary>
        public System.String RUserOrgRleObsInd
        {
            get;
             			set;
        }

        /// <summary>
        /// Gets or sets the SiteMapNodeID field.
        /// </summary>
        public System.Int32 SiteMapNodeID
        {
            get;
             			set;
        }

        /// <summary>
        /// Gets or sets the URLPath field.
        /// </summary>
        public System.String URLPath
        {
            get;
             			set;
        }

        /// <summary>
        /// Gets or sets the UserId field.
        /// </summary>
        public System.String UserId
        {
            get;
             			set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            AuthorizeURLViewEntity toCompareWith = obj as AuthorizeURLViewEntity;
            return toCompareWith == null ? false : ((this.SiteMapNodeID == toCompareWith.SiteMapNodeID));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.SiteMapNodeID.GetHashCode();
            return toReturn;
        }

        public override string ToString()
        {
            return 		"RoleCode=" + RoleCode + "--" +
            "URLPath=" + URLPath + "--" +
            "UserId=" + UserId + "--" +
            "RanaGrpObsInd=" + RanaGrpObsInd + "--" +
            "RUserOrgRleObsInd=" + RUserOrgRleObsInd + "--" +
            "SiteMapNodeID=" + SiteMapNodeID + "--" +
            "";
        }

        #endregion Methods
    }
}