//#region Header

////------------------------------------------------------------------------------
//// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
////------------------------------------------------------------------------------

//#endregion Header

//namespace AllInOne.Legal.Domain.Enforcement
//{
//    using System;

//    /// <summary>Class which represents the entity 'Enforcement.EMSAdmCharge'</summary>
//    [Serializable]
//    public class EMSAdmChargeEntity : IEnforcementEntity
//    {
//        #region Properties

//        /// <summary>Gets or sets the AdvertFee field. </summary>
//        public Nullable<System.Decimal> AdvertFee
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the AgencyFee field. </summary>
//        public Nullable<System.Decimal> AgencyFee
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the AppraiserFee field. </summary>
//        public Nullable<System.Decimal> AppraiserFee
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the BankTpt field. </summary>
//        public Nullable<System.Decimal> BankTpt
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the BerthCharges field. </summary>
//        public Nullable<System.Decimal> BerthCharges
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the CrewWages field. </summary>
//        public Nullable<System.Decimal> CrewWages
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the DeliveryFee field. </summary>
//        public Nullable<System.Decimal> DeliveryFee
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the EMSAccountId field. </summary>
//        public System.String EMSAccountId
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the EMSAdmChargeId field. </summary>
//        public System.String EMSAdmChargeId
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the GazetteNotice field. </summary>
//        public Nullable<System.Decimal> GazetteNotice
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the GuardCharges field. </summary>
//        public Nullable<System.Decimal> GuardCharges
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the IsCharged field. </summary>
//        public YesNo IsCharged
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the LastModifiedBy field. </summary>
//        public System.String LastModifiedBy
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the LastModifiedDate field. </summary>
//        public System.DateTime LastModifiedDate
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the NotaryFee field. </summary>
//        public Nullable<System.Decimal> NotaryFee
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the ObsInd field. </summary>
//        public YesNo ObsInd
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the OtherExpenses field. </summary>
//        public Nullable<System.Decimal> OtherExpenses
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the PSAPortDues field. </summary>
//        public Nullable<System.Decimal> PSAPortDues
//        {
//            get;
//            set;
//        }

//        /// <summary>Gets or sets the EMSPaymentVoucherId field. </summary>
//        public System.String EMSPaymentVoucherId
//        {
//            get;
//            set;
//        }

//        #endregion Properties

//        #region Methods

//        /// <summary>Determines whether the specified object is equal to this instance.</summary>
//        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
//        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
//        public override bool Equals(object obj)
//        {
//            if (obj == null)
//            {
//                return false;
//            }
//            EMSAdmChargeEntity toCompareWith = obj as EMSAdmChargeEntity;
//            return toCompareWith == null ? false : ((this.EMSAdmChargeId == toCompareWith.EMSAdmChargeId));
//        }

//        /// <summary>Returns a hash code for this instance.</summary>
//        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
//        public override int GetHashCode()
//        {
//            int toReturn = base.GetHashCode();
//            toReturn ^= this.EMSAdmChargeId.GetHashCode();
//            return toReturn;
//        }

//        #endregion Methods
//    }
//}