#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Enforcement
{
    using System;

    using AllInOne.Legal.Domain.Case;
    using AllInOne.Legal.Domain.SubCase;

    /// <summary>Class which represents the entity 'Enforcement.EMSAccount'</summary>
    [Serializable]
    public class MOMRegisterViewEntity : IEnforcementEntity
    {
        #region Fields

        private String caseInfoId;
        private String caseNo;
        private String docCode;
        private String docId;
        private DateTime? filingDateTime;
        private String momSctCaseNo;
        private String woeMomSctInfoId;

        #endregion Fields

        #region Constructors

        public MOMRegisterViewEntity(string WoeMomSctInfoId, DateTime? FilingDateTime, string DocId,
            string DocCode, string MomSctCaseNo, string CaseInfoId, string CaseNo)
        {
            woeMomSctInfoId = WoeMomSctInfoId;
            filingDateTime = FilingDateTime;
            docId = DocId;
            docCode = DocCode;
            momSctCaseNo = MomSctCaseNo;
            caseInfoId = CaseInfoId;
            caseNo = CaseNo;
        }

        #endregion Constructors

        #region Properties

        public String CaseInfoId
        {
            get { return caseInfoId; }
        }

        public String CaseNo
        {
            get { return caseNo; }
        }

        public String DocCode
        {
            get { return docCode; }
        }

        public String DocId
        {
            get { return docId; }
        }

        public DateTime? FilingDateTime
        {
            get { return filingDateTime; }
        }

        public String MomSctCaseNo
        {
            get { return momSctCaseNo; }
        }

        public String WoeMomSctInfoId
        {
            get { return woeMomSctInfoId; }
        }

        #endregion Properties
    }
}