#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Enforcement
{
    using System;

    using AllInOne.Legal.Domain.Case;
    using AllInOne.Legal.Domain.Master;

    /// <summary>Class which represents the entity 'Enforcement.EMSPaymentVoucherMisc'</summary>
    [Serializable]
    public class EMSPaymentVoucherMiscEntity : IEnforcementEntity
    {
        #region Properties

        /// <summary>Gets or sets the AddLess field. </summary>
        public virtual AddLess AddLess
        {
            get;
            set;
        }

        /// <summary>Gets or sets the Amount field. </summary>
        public virtual System.Decimal Amount
        {
            get;
            set;
        }

        /// <summary>Gets or sets the Description field. </summary>
        public virtual System.String Description
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSPaymentVoucherFinalId field. </summary>
        public System.String EMSPaymentVoucherFinalId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSPaymentVoucherMiscId field. </summary>
        public virtual System.String EMSPaymentVoucherMiscId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            EMSPaymentVoucherMiscEntity toCompareWith = obj as EMSPaymentVoucherMiscEntity;
            return toCompareWith == null ? false : ((this.EMSPaymentVoucherMiscId == toCompareWith.EMSPaymentVoucherMiscId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSPaymentVoucherMiscId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}