#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Enforcement
{
    using System;

    /// <summary>Class which represents the entity 'Enforcement.EMSPaymentVoucherAdm'</summary>
    [Serializable]
    public class EMSPaymentVoucherAdmEntity : IEnforcementEntity
    {
        #region Properties

        /// <summary>Gets or sets the AdvertFee field. </summary>
        public Nullable<System.Decimal> AdvertFee
        {
            get;
            set;
        }

        /// <summary>Gets or sets the AuctioneerCharges field. </summary>
        public Nullable<System.Decimal> AuctioneerCharges
        {
            get;
            set;
        }

        /// <summary>Gets or sets the BunkerComm field. </summary>
        public Nullable<System.Decimal> BunkerComm
        {
            get;
            set;
        }

        /// <summary>Gets or sets the BunkerSaleValue field. </summary>
        public Nullable<System.Decimal> BunkerSaleValue
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSAdmChargeId field. </summary>
        public System.String EMSAdmChargeId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSPaymentVoucherAdmId field. </summary>
        public System.String EMSPaymentVoucherAdmId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSPaymentVoucherFinalId field. </summary>
        public System.String EMSPaymentVoucherFinalId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public System.String LastModifiedBy
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public System.DateTime LastModifiedDate
        {
            get;
            set;
        }

        /// <summary>Gets or sets the SheriffComm field. </summary>
        public Nullable<System.Decimal> SheriffComm
        {
            get;
            set;
        }

        /// <summary>Gets or sets the VesselSaleValue field. </summary>
        public Nullable<System.Decimal> VesselSaleValue
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            EMSPaymentVoucherAdmEntity toCompareWith = obj as EMSPaymentVoucherAdmEntity;
            return toCompareWith == null ? false : ((this.EMSPaymentVoucherAdmId == toCompareWith.EMSPaymentVoucherAdmId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSPaymentVoucherAdmId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}