#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'SubCaseSpecific.AccountantsReportInfo'</summary>
    public partial class AccountantsReportInfo
    {
        #region Fields

        private System.String _accountantsReportInfoId;
        private Nullable<System.DateTime> _accountingFromDate;
        private Nullable<System.DateTime> _accountingToDate;
        private System.String _certainTrivialBreaches;
        private System.String _doesAcctRptComplyS73LPA;
        private System.String _doesHaveDiffInComparision;
        private System.String _idNumberOfAccountant;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _matterSetOutFirstSection;
        private System.String _matterSetOutSecondSection;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="AccountantsReportInfo"/> class.</summary>
        public AccountantsReportInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the AccountantsReportInfoId field. </summary>
        public virtual System.String AccountantsReportInfoId
        {
            get { return _accountantsReportInfoId; }
            set { _accountantsReportInfoId = value; }
        }

        /// <summary>Gets or sets the AccountingFromDate field. </summary>
        public virtual Nullable<System.DateTime> AccountingFromDate
        {
            get { return _accountingFromDate; }
            set { _accountingFromDate = value; }
        }

        /// <summary>Gets or sets the AccountingToDate field. </summary>
        public virtual Nullable<System.DateTime> AccountingToDate
        {
            get { return _accountingToDate; }
            set { _accountingToDate = value; }
        }

        /// <summary>Gets or sets the CertainTrivialBreaches field. </summary>
        public virtual System.String CertainTrivialBreaches
        {
            get { return _certainTrivialBreaches; }
            set { _certainTrivialBreaches = value; }
        }

        /// <summary>Gets or sets the DoesAcctRptComplyS73LPA field. </summary>
        public virtual System.String DoesAcctRptComplyS73LPA
        {
            get { return _doesAcctRptComplyS73LPA; }
            set { _doesAcctRptComplyS73LPA = value; }
        }

        /// <summary>Gets or sets the DoesHaveDiffInComparision field. </summary>
        public virtual System.String DoesHaveDiffInComparision
        {
            get { return _doesHaveDiffInComparision; }
            set { _doesHaveDiffInComparision = value; }
        }

        /// <summary>Gets or sets the IdNumberOfAccountant field. </summary>
        public virtual System.String IdNumberOfAccountant
        {
            get { return _idNumberOfAccountant; }
            set { _idNumberOfAccountant = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MatterSetOutFirstSection field. </summary>
        public virtual System.String MatterSetOutFirstSection
        {
            get { return _matterSetOutFirstSection; }
            set { _matterSetOutFirstSection = value; }
        }

        /// <summary>Gets or sets the MatterSetOutSecondSection field. </summary>
        public virtual System.String MatterSetOutSecondSection
        {
            get { return _matterSetOutSecondSection; }
            set { _matterSetOutSecondSection = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            AccountantsReportInfo toCompareWith = obj as AccountantsReportInfo;
            return toCompareWith == null ? false : ((this.AccountantsReportInfoId == toCompareWith.AccountantsReportInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.AccountantsReportInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}