#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Case.CasePartyLACDetail'</summary>
    public partial class CasePartyLACDetail : ICase
    {
        #region Fields

        private CaseParty _caseParty;
        private System.String _cPLACDetailId;

        //private DocumentInfo _documentInfo;
        private System.String _filedUserType;

        //private LACDocumentDetail _lACDocumentDetail;
        //private LACInfo _lACInfo;
        private System.String _lACRefStatus;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _lFGroupCode;
        private System.DateTime _startDate;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="CasePartyLACDetail"/> class.</summary>
        public CasePartyLACDetail()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Case.CasePartyLACDetail.CaseParty - Case.CaseParty.CasePartyLACDetails (m:1)'</summary>
        public virtual CaseParty CaseParty
        {
            get { return _caseParty; }
            set { _caseParty = value; }
        }

        /// <summary>Gets or sets the CPLACDetailId field. </summary>
        public virtual System.String CPLACDetailId
        {
            get { return _cPLACDetailId; }
            set { _cPLACDetailId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Case.CasePartyLACDetail.DocumentInfo - Document.DocumentInfo.CasePartyLACDetails (m:1)'</summary>
        public virtual String DocId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the FiledUserType field. </summary>
        public virtual System.String FiledUserType
        {
            get { return _filedUserType; }
            set { _filedUserType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Case.CasePartyLACDetail.LACDocumentDetail - LAP.LACDocumentDetail.CasePartyLACDetails (m:1)'</summary>
        public virtual String LACDocDetailId
        {
            get;
            set;
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Case.CasePartyLACDetail.LACInfo - LAP.LACInfo.CasePartyLACDetails (m:1)'</summary>
        public virtual String LACInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LACRefStatus field. </summary>
        public virtual System.String LACRefStatus
        {
            get { return _lACRefStatus; }
            set { _lACRefStatus = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the LFGroupCode field. </summary>
        public virtual System.String LFGroupCode
        {
            get { return _lFGroupCode; }
            set { _lFGroupCode = value; }
        }

        /// <summary>Gets or sets the StartDate field. </summary>
        public virtual System.DateTime StartDate
        {
            get { return _startDate; }
            set { _startDate = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            CasePartyLACDetail toCompareWith = obj as CasePartyLACDetail;
            return toCompareWith == null ? false : ((this.CPLACDetailId == toCompareWith.CPLACDetailId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CPLACDetailId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}