#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.CertSecurityOfCostsInfo'</summary>
    public partial class CertSecurityOfCostsInfo : ICommon
    {
        #region Fields

        private System.String _certSecurityOfCostsInfoId;
        private DocumentInfo _documentInfo;
        private Nullable<System.Decimal> _dRIAmount;
        private System.String _dRINumber;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private Nullable<System.Int64> _subCaseInfoId;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="CertSecurityOfCostsInfo"/> class.</summary>
        public CertSecurityOfCostsInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CertSecurityOfCostsInfoId field. </summary>
        public virtual System.String CertSecurityOfCostsInfoId
        {
            get { return _certSecurityOfCostsInfoId; }
            set { _certSecurityOfCostsInfoId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.CertSecurityOfCostsInfo.DocumentInfo - Document.DocumentInfo.CertSecurityOfCostsInfos (m:1)'</summary>
        public virtual DocumentInfo DocumentInfo
        {
            get { return _documentInfo; }
            set { _documentInfo = value; }
        }

        /// <summary>Gets or sets the DRIAmount field. </summary>
        public virtual Nullable<System.Decimal> DRIAmount
        {
            get { return _dRIAmount; }
            set { _dRIAmount = value; }
        }

        /// <summary>Gets or sets the DRINumber field. </summary>
        public virtual System.String DRINumber
        {
            get { return _dRINumber; }
            set { _dRINumber = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the SubCaseInfoId field. </summary>
        public virtual Nullable<System.Int64> SubCaseInfoId
        {
            get { return _subCaseInfoId; }
            set { _subCaseInfoId = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            CertSecurityOfCostsInfo toCompareWith = obj as CertSecurityOfCostsInfo;
            return toCompareWith == null ? false : ((this.CertSecurityOfCostsInfoId == toCompareWith.CertSecurityOfCostsInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CertSecurityOfCostsInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}