#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Document.DocCasePartyAICDetail'</summary>
    public partial class DocCasePartyAICDetail : IDocument
    {
        #region Fields

        private System.String _addressAvailabilityInd;
        private System.Collections.Generic.ICollection<ADMWAInfo> _aDMWAInfos;
        private System.String _companyName;
        private Nullable<System.DateTime> _dateOfRegistration;
        private System.String _dCPAICID;

        //private DocCaseParty _docCaseParty;
        private System.String _dCPID;
        private System.Collections.Generic.ICollection<DocCasePartyAICAddress> _docCasePartyAICAddresses;
        private System.Collections.Generic.ICollection<DocCasePartyAICAlias> _docCasePartyAICAliases;
        private System.String _formerCompanyName;
        private System.String _formerPersonName;
        private System.String _fullName;
        private System.String _idNumber;
        private System.String _idRemarks;
        private System.String _iMONumber;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MActingInCapacity _mActingInCapacity;
        private MPersonIDType _mDCPAICDCompanyIdTypeCode;
        private MCountry _mDCPAICDCountryOfRegistration;
        private MCountry _mDCPAICDIdCountryCode;
        private MPersonIDType _mDCPAICDPersonIdTypeCode;
        private MEntityType _mEntityType;
        private MGender _mGender;
        private MPersonIDGroup _mPersonIDGroup;
        private System.String _portOfRegistration;
        private System.String _registrationNumber;
        private System.String _uEN;
        private System.String _vesselIdType;
        private System.String _vesselName;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="DocCasePartyAICDetail"/> class.</summary>
        public DocCasePartyAICDetail()
            : base()
        {
            _docCasePartyAICAddresses = new System.Collections.Generic.HashSet<DocCasePartyAICAddress>();
            _docCasePartyAICAliases = new System.Collections.Generic.HashSet<DocCasePartyAICAlias>();
            _aDMWAInfos = new System.Collections.Generic.HashSet<ADMWAInfo>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the AddressAvailabilityInd field. </summary>
        public virtual System.String AddressAvailabilityInd
        {
            get { return _addressAvailabilityInd; }
            set { _addressAvailabilityInd = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'SubCaseSpecific.ADMWAInfo.DocCasePartyAICDetail - Document.DocCasePartyAICDetail.ADMWAInfos (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<ADMWAInfo> ADMWAInfos
        {
            get { return _aDMWAInfos; }
            set { _aDMWAInfos = value; }
        }

        /// <summary>Gets or sets the CompanyName field. </summary>
        public virtual System.String CompanyName
        {
            get { return _companyName; }
            set { _companyName = value; }
        }

        /// <summary>Gets or sets the DateOfRegistration field. </summary>
        public virtual Nullable<System.DateTime> DateOfRegistration
        {
            get { return _dateOfRegistration; }
            set { _dateOfRegistration = value; }
        }

        /// <summary>Gets or sets the DCPAICID field. </summary>
        public virtual System.String DCPAICID
        {
            get { return _dCPAICID; }
            set { _dCPAICID = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.DocCaseParty - Document.DocCaseParty.DocCasePartyAICDetails (m:1)'</summary>
        //public virtual DocCaseParty DocCaseParty
        //{
        //    get { return _docCaseParty; }
        //    set { _docCaseParty = value; }
        //}
        /// <summary>Gets or sets the DCPID field. </summary>
        public virtual System.String DCPID
        {
            get { return _dCPID; }
            set { _dCPID = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICAddress.DocCasePartyAICDetail - Document.DocCasePartyAICDetail.DocCasePartyAICAddresses (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<DocCasePartyAICAddress> DocCasePartyAICAddresses
        {
            get { return _docCasePartyAICAddresses; }
            set { _docCasePartyAICAddresses = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICAlias.DocCasePartyAICDetail - Document.DocCasePartyAICDetail.DocCasePartyAICAliases (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<DocCasePartyAICAlias> DocCasePartyAICAliases
        {
            get { return _docCasePartyAICAliases; }
            set { _docCasePartyAICAliases = value; }
        }

        /// <summary>Gets or sets the FormerCompanyName field. </summary>
        public virtual System.String FormerCompanyName
        {
            get { return _formerCompanyName; }
            set { _formerCompanyName = value; }
        }

        /// <summary>Gets or sets the FormerPersonName field. </summary>
        public virtual System.String FormerPersonName
        {
            get { return _formerPersonName; }
            set { _formerPersonName = value; }
        }

        /// <summary>Gets or sets the FullName field. </summary>
        public virtual System.String FullName
        {
            get { return _fullName; }
            set { _fullName = value; }
        }

        /// <summary>Gets or sets the IdNumber field. </summary>
        public virtual System.String IdNumber
        {
            get { return _idNumber; }
            set { _idNumber = value; }
        }

        /// <summary>Gets or sets the IdRemarks field. </summary>
        public virtual System.String IdRemarks
        {
            get { return _idRemarks; }
            set { _idRemarks = value; }
        }

        /// <summary>Gets or sets the IMONumber field. </summary>
        public virtual System.String IMONumber
        {
            get { return _iMONumber; }
            set { _iMONumber = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MActingInCapacity - Master.MActingInCapacity.DocCasePartyAICDetails (m:1)'</summary>
        public virtual MActingInCapacity MActingInCapacity
        {
            get { return _mActingInCapacity; }
            set { _mActingInCapacity = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MDCPAICDCompanyIdTypeCode - Master.MPersonIDType.MDCPAICDCompanyIdTypeCode (m:1)'</summary>
        public virtual MPersonIDType MDCPAICDCompanyIdTypeCode
        {
            get { return _mDCPAICDCompanyIdTypeCode; }
            set { _mDCPAICDCompanyIdTypeCode = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MDCPAICDCountryOfRegistration - Master.MCountry.MDCPAICDCountryOfRegistration (m:1)'</summary>
        public virtual MCountry MDCPAICDCountryOfRegistration
        {
            get { return _mDCPAICDCountryOfRegistration; }
            set { _mDCPAICDCountryOfRegistration = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MDCPAICDIdCountryCode - Master.MCountry.MDCPAICDIdCountryCode (m:1)'</summary>
        public virtual MCountry MDCPAICDIdCountryCode
        {
            get { return _mDCPAICDIdCountryCode; }
            set { _mDCPAICDIdCountryCode = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MDCPAICDPersonIdTypeCode - Master.MPersonIDType.MDCPAICDPersonIdTypeCode (m:1)'</summary>
        public virtual MPersonIDType MDCPAICDPersonIdTypeCode
        {
            get { return _mDCPAICDPersonIdTypeCode; }
            set { _mDCPAICDPersonIdTypeCode = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MEntityType - Master.MEntityType.DocCasePartyAICDetails (m:1)'</summary>
        public virtual MEntityType MEntityType
        {
            get { return _mEntityType; }
            set { _mEntityType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MGender - Master.MGender.DocCasePartyAICDetails (m:1)'</summary>
        public virtual MGender MGender
        {
            get { return _mGender; }
            set { _mGender = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Document.DocCasePartyAICDetail.MPersonIDGroup - Master.MPersonIDGroup.DocCasePartyAICDetails (m:1)'</summary>
        public virtual MPersonIDGroup MPersonIDGroup
        {
            get { return _mPersonIDGroup; }
            set { _mPersonIDGroup = value; }
        }

        /// <summary>Gets or sets the PortOfRegistration field. </summary>
        public virtual System.String PortOfRegistration
        {
            get { return _portOfRegistration; }
            set { _portOfRegistration = value; }
        }

        /// <summary>Gets or sets the RegistrationNumber field. </summary>
        public virtual System.String RegistrationNumber
        {
            get { return _registrationNumber; }
            set { _registrationNumber = value; }
        }

        /// <summary>Gets or sets the UEN field. </summary>
        public virtual System.String UEN
        {
            get { return _uEN; }
            set { _uEN = value; }
        }

        /// <summary>Gets or sets the VesselIdType field. </summary>
        public virtual System.String VesselIdType
        {
            get { return _vesselIdType; }
            set { _vesselIdType = value; }
        }

        /// <summary>Gets or sets the VesselName field. </summary>
        public virtual System.String VesselName
        {
            get { return _vesselName; }
            set { _vesselName = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            DocCasePartyAICDetail toCompareWith = obj as DocCasePartyAICDetail;
            return toCompareWith == null ? false : ((this.DCPAICID == toCompareWith.DCPAICID));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.DCPAICID.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}