#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Enforcement.EMSFileMovement'</summary>
    public partial class EMSFileMovement : IEnforcement
    {
        #region Fields

        private JudicialUser _bailiff;
        private EMSAccount _eMSAccount;
        private System.String _eMSFileMovementId;
        private System.DateTime _fileMoveDate;
        private System.String _fileMoveDesc;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _obsInd;
        private System.String _remarks;
        private JudicialUser _updatedBy;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="EMSFileMovement"/> class.</summary>
        public EMSFileMovement()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the Bailiff field. </summary>
        public virtual JudicialUser Bailiff
        {
            get { return _bailiff; }
            set { _bailiff = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Enforcement.EMSFileMovement.EMSAccount - Enforcement.EMSAccount.EMSFileMovements (m:1)'</summary>
        public virtual EMSAccount EMSAccount
        {
            get { return _eMSAccount; }
            set { _eMSAccount = value; }
        }

        /// <summary>Gets or sets the EMSFileMovementId field. </summary>
        public virtual System.String EMSFileMovementId
        {
            get { return _eMSFileMovementId; }
            set { _eMSFileMovementId = value; }
        }

        /// <summary>Gets or sets the FileMoveDate field. </summary>
        public virtual System.DateTime FileMoveDate
        {
            get { return _fileMoveDate; }
            set { _fileMoveDate = value; }
        }

        /// <summary>Gets or sets the FileMoveDesc field. </summary>
        public virtual System.String FileMoveDesc
        {
            get { return _fileMoveDesc; }
            set { _fileMoveDesc = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the Remarks field. </summary>
        public virtual System.String Remarks
        {
            get { return _remarks; }
            set { _remarks = value; }
        }

        /// <summary>Gets or sets the UpdatedBy field. </summary>
        public virtual JudicialUser UpdatedBy
        {
            get { return _updatedBy; }
            set { _updatedBy = value; }
        }

        public virtual string DocId
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            EMSFileMovement toCompareWith = obj as EMSFileMovement;
            return toCompareWith == null ? false : ((this.EMSFileMovementId == toCompareWith.EMSFileMovementId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSFileMovementId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}