#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Enforcement.EMSPayment'</summary>
    public partial class EMSPayment : IEnforcement
    {
        #region Fields

        private System.Collections.Generic.ICollection<EMSPaymentCheque> _eMSPaymentCheques;
        private System.String _eMSPaymentId;
        private EMSPaymentVoucher _eMSPaymentVoucher;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MEMSLedger _mEMSLedger;
        private MEMSNatureOfPayment _mEMSNatureOfPayment;
        private System.String _obsInd;
        private System.String _payeeName;
        private Nullable<System.Decimal> _paymentAmount;
        private System.String _paymentStatus;
        private System.String _type;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="EMSPayment"/> class.</summary>
        public EMSPayment()
            : base()
        {
            _eMSPaymentCheques = new System.Collections.Generic.HashSet<EMSPaymentCheque>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Enforcement.EMSPaymentCheque.EMSPayment - Enforcement.EMSPayment.EMSPaymentCheques (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<EMSPaymentCheque> EMSPaymentCheques
        {
            get { return _eMSPaymentCheques; }
            set { _eMSPaymentCheques = value; }
        }

        /// <summary>Gets or sets the EMSPaymentId field. </summary>
        public virtual System.String EMSPaymentId
        {
            get { return _eMSPaymentId; }
            set { _eMSPaymentId = value; }
        }

        /// <summary>Gets or sets the EMSPaymentVoucher field. </summary>
        public virtual EMSPaymentVoucher EMSPaymentVoucher
        {
            get { return _eMSPaymentVoucher; }
            set { _eMSPaymentVoucher = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MEMSLedger field. </summary>
        public virtual MEMSLedger MEMSLedger
        {
            get { return _mEMSLedger; }
            set { _mEMSLedger = value; }
        }

        /// <summary>Gets or sets the MEMSNatureOfPayment field. </summary>
        public virtual MEMSNatureOfPayment MEMSNatureOfPayment
        {
            get { return _mEMSNatureOfPayment; }
            set { _mEMSNatureOfPayment = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the PayeeName field. </summary>
        public virtual System.String PayeeName
        {
            get { return _payeeName; }
            set { _payeeName = value; }
        }

        /// <summary>Gets or sets the PaymentAmount field. </summary>
        public virtual Nullable<System.Decimal> PaymentAmount
        {
            get { return _paymentAmount; }
            set { _paymentAmount = value; }
        }

        /// <summary>Gets or sets the PaymentStatus field. </summary>
        public virtual System.String PaymentStatus
        {
            get { return _paymentStatus; }
            set { _paymentStatus = value; }
        }

        /// <summary>Gets or sets the Type field. </summary>
        public virtual System.String Type
        {
            get { return _type; }
            set { _type = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            EMSPayment toCompareWith = obj as EMSPayment;
            return toCompareWith == null ? false : ((this.EMSPaymentId == toCompareWith.EMSPaymentId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSPaymentId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}