#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Enforcement.EMSSaleAuctioneer'</summary>
    public partial class EMSSaleAuctioneer : IEnforcement
    {
        #region Fields

        private Nullable<System.Decimal> _auctioneerCharges;
        private Nullable<System.DateTime> _auctioneerDateEngaged;
        private System.String _eMSSaleAuctioneerId;
        private EMSSale _eMSSale;
        private EMSPaymentVoucher _eMSPaymentVoucher;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MEMSAuctioneer _mEMSAuctioneer;
        private System.String _otherAuctioneer;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="EMSSaleAuctioneer"/> class.</summary>
        public EMSSaleAuctioneer()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the AuctioneerCharges field. </summary>
        public virtual Nullable<System.Decimal> AuctioneerCharges
        {
            get { return _auctioneerCharges; }
            set { _auctioneerCharges = value; }
        }

        /// <summary>Gets or sets the AuctioneerDateEngaged field. </summary>
        public virtual Nullable<System.DateTime> AuctioneerDateEngaged
        {
            get { return _auctioneerDateEngaged; }
            set { _auctioneerDateEngaged = value; }
        }

        /// <summary>Gets or sets the EMSSaleAuctioneerId field. </summary>
        public virtual System.String EMSSaleAuctioneerId
        {
            get { return _eMSSaleAuctioneerId; }
            set { _eMSSaleAuctioneerId = value; }
        }

        /// <summary>Gets or sets the EMSSale field. </summary>
        public virtual EMSSale EMSSale
        {
            get { return _eMSSale; }
            set { _eMSSale = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MEMSAuctioneer field. </summary>
        public virtual MEMSAuctioneer MEMSAuctioneer
        {
            get { return _mEMSAuctioneer; }
            set { _mEMSAuctioneer = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Enforcement.EMSSaleAuctioneer.EMSPaymentVoucher - Enforcement.EMSPaymentVoucher.EMSSaleAuctioneers (m:1)'</summary>
        public virtual EMSPaymentVoucher EMSPaymentVoucher
        {
            get { return _eMSPaymentVoucher; }
            set { _eMSPaymentVoucher = value; }
        }

        /// <summary>Gets or sets the OtherAuctioneer field. </summary>
        public virtual System.String OtherAuctioneer
        {
            get { return _otherAuctioneer; }
            set { _otherAuctioneer = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            EMSSaleAuctioneer toCompareWith = obj as EMSSaleAuctioneer;
            return toCompareWith == null ? false : ((this.EMSSaleAuctioneerId == toCompareWith.EMSSaleAuctioneerId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSSaleAuctioneerId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}