#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.Liquidator'</summary>
    public partial class Liquidator : ICommon
    {
        #region Fields

        private System.String _companyName;
        private System.String _contactTypeInd;
        private Nullable<System.DateTime> _dateOfRegistration;
        private System.String _email;
        private System.String _faxAreaCode;
        private System.String _faxCountryCode;
        private System.String _faxNumber;
        private System.String _formerCompanyName;
        private System.String _formerPersonName;
        private System.String _fullName;
        private System.String _idNumber;
        private System.String _idRemarks;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.Collections.Generic.ICollection<LiquidatorAddress> _liquidatorAddresses;
        private System.Collections.Generic.ICollection<LiquidatorAlias> _liquidatorAliases;
        private System.String _liquidatorId;
        private System.Collections.Generic.ICollection<LiquidatorPIC> _liquidatorPICs;
        private MEntityType _mEntityType;
        private MGender _mGender;
        private MPersonIDType _mLCompanyIdType;
        private MCountry _mLIdCountry;
        private MCountry _mLIdCountryOfRegistration;
        private MPersonIDType _mLPersonIdType;
        private System.String _mobileCountryCode;
        private System.String _mobileNumber;
        private MPersonIDGroup _mPersonIDGroup;
        private System.String _submissionGroupId;
        private System.String _telAreaCode;
        private System.String _telCountryCode;
        private System.String _telNumber;
        private System.String _uEN;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="Liquidator"/> class.</summary>
        public Liquidator()
            : base()
        {
            _liquidatorAddresses = new System.Collections.Generic.HashSet<LiquidatorAddress>();
            _liquidatorAliases = new System.Collections.Generic.HashSet<LiquidatorAlias>();
            _liquidatorPICs = new System.Collections.Generic.HashSet<LiquidatorPIC>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CompanyName field. </summary>
        public virtual System.String CompanyName
        {
            get { return _companyName; }
            set { _companyName = value; }
        }

        /// <summary>Gets or sets the ContactTypeInd field. </summary>
        public virtual System.String ContactTypeInd
        {
            get { return _contactTypeInd; }
            set { _contactTypeInd = value; }
        }

        /// <summary>Gets or sets the DateOfRegistration field. </summary>
        public virtual Nullable<System.DateTime> DateOfRegistration
        {
            get { return _dateOfRegistration; }
            set { _dateOfRegistration = value; }
        }

        /// <summary>Gets or sets the Email field. </summary>
        public virtual System.String Email
        {
            get { return _email; }
            set { _email = value; }
        }

        /// <summary>Gets or sets the FaxAreaCode field. </summary>
        public virtual System.String FaxAreaCode
        {
            get { return _faxAreaCode; }
            set { _faxAreaCode = value; }
        }

        /// <summary>Gets or sets the FaxCountryCode field. </summary>
        public virtual System.String FaxCountryCode
        {
            get { return _faxCountryCode; }
            set { _faxCountryCode = value; }
        }

        /// <summary>Gets or sets the FaxNumber field. </summary>
        public virtual System.String FaxNumber
        {
            get { return _faxNumber; }
            set { _faxNumber = value; }
        }

        /// <summary>Gets or sets the FormerCompanyName field. </summary>
        public virtual System.String FormerCompanyName
        {
            get { return _formerCompanyName; }
            set { _formerCompanyName = value; }
        }

        /// <summary>Gets or sets the FormerPersonName field. </summary>
        public virtual System.String FormerPersonName
        {
            get { return _formerPersonName; }
            set { _formerPersonName = value; }
        }

        /// <summary>Gets or sets the FullName field. </summary>
        public virtual System.String FullName
        {
            get { return _fullName; }
            set { _fullName = value; }
        }

        /// <summary>Gets or sets the IdNumber field. </summary>
        public virtual System.String IdNumber
        {
            get { return _idNumber; }
            set { _idNumber = value; }
        }

        /// <summary>Gets or sets the IdRemarks field. </summary>
        public virtual System.String IdRemarks
        {
            get { return _idRemarks; }
            set { _idRemarks = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.LiquidatorAddress.Liquidator - Common.Liquidator.LiquidatorAddresses (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<LiquidatorAddress> LiquidatorAddresses
        {
            get { return _liquidatorAddresses; }
            set { _liquidatorAddresses = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.LiquidatorAlias.Liquidator - Common.Liquidator.LiquidatorAliases (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<LiquidatorAlias> LiquidatorAliases
        {
            get { return _liquidatorAliases; }
            set { _liquidatorAliases = value; }
        }

        /// <summary>Gets or sets the LiquidatorId field. </summary>
        public virtual System.String LiquidatorId
        {
            get { return _liquidatorId; }
            set { _liquidatorId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.LiquidatorPIC.Liquidator - Common.Liquidator.LiquidatorPICs (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<LiquidatorPIC> LiquidatorPICs
        {
            get { return _liquidatorPICs; }
            set { _liquidatorPICs = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MEntityType - Master.MEntityType.Liquidators (m:1)'</summary>
        public virtual MEntityType MEntityType
        {
            get { return _mEntityType; }
            set { _mEntityType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MGender - Master.MGender.Liquidators (m:1)'</summary>
        public virtual MGender MGender
        {
            get { return _mGender; }
            set { _mGender = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MLCompanyIdType - Master.MPersonIDType.MLCompanyIdType (m:1)'</summary>
        public virtual MPersonIDType MLCompanyIdType
        {
            get { return _mLCompanyIdType; }
            set { _mLCompanyIdType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MLIdCountry - Master.MCountry.MLIdCountry (m:1)'</summary>
        public virtual MCountry MLIdCountry
        {
            get { return _mLIdCountry; }
            set { _mLIdCountry = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MLIdCountryOfRegistration - Master.MCountry.MLIdCountryOfRegistration (m:1)'</summary>
        public virtual MCountry MLIdCountryOfRegistration
        {
            get { return _mLIdCountryOfRegistration; }
            set { _mLIdCountryOfRegistration = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MLPersonIdType - Master.MPersonIDType.MLPersonIdType (m:1)'</summary>
        public virtual MPersonIDType MLPersonIdType
        {
            get { return _mLPersonIdType; }
            set { _mLPersonIdType = value; }
        }

        /// <summary>Gets or sets the MobileCountryCode field. </summary>
        public virtual System.String MobileCountryCode
        {
            get { return _mobileCountryCode; }
            set { _mobileCountryCode = value; }
        }

        /// <summary>Gets or sets the MobileNumber field. </summary>
        public virtual System.String MobileNumber
        {
            get { return _mobileNumber; }
            set { _mobileNumber = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.Liquidator.MPersonIDGroup - Master.MPersonIDGroup.Liquidators (m:1)'</summary>
        public virtual MPersonIDGroup MPersonIDGroup
        {
            get { return _mPersonIDGroup; }
            set { _mPersonIDGroup = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        /// <summary>Gets or sets the TelAreaCode field. </summary>
        public virtual System.String TelAreaCode
        {
            get { return _telAreaCode; }
            set { _telAreaCode = value; }
        }

        /// <summary>Gets or sets the TelCountryCode field. </summary>
        public virtual System.String TelCountryCode
        {
            get { return _telCountryCode; }
            set { _telCountryCode = value; }
        }

        /// <summary>Gets or sets the TelNumber field. </summary>
        public virtual System.String TelNumber
        {
            get { return _telNumber; }
            set { _telNumber = value; }
        }

        /// <summary>Gets or sets the UEN field. </summary>
        public virtual System.String UEN
        {
            get { return _uEN; }
            set { _uEN = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            Liquidator toCompareWith = obj as Liquidator;
            return toCompareWith == null ? false : ((this.LiquidatorId == toCompareWith.LiquidatorId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.LiquidatorId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}