#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MDocControlForum'</summary>
    public partial class MDocControlForum
    {


        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MDocControlForum"/> class.</summary>
        public MDocControlForum()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        public virtual string ForumId { get; set; }
        public virtual MDocCode MDocCode { get; set; }
        public virtual MCaseType CaseTypeCode { get; set; }
        public virtual string DocPrefix { get; set; }
        public virtual string DIYInd { get; set; }
        public virtual string HearingInd { get; set; }
        public virtual string AutoAcceptInd { get; set; }
        public virtual string SpecialReqInd { get; set; }
        public virtual string ComDocGroupInd { get; set; }
        public virtual string SubDocGroupInd { get; set; }
        public virtual string IsMandatory { get; set; }
        public virtual string AmendPartyInd { get; set; }
        public virtual string FeeRuleCode { get; set; }
        public virtual string DocControlId { get; set; }
        public virtual MCaseType SubCaseTypeCode { get; set; }
        public virtual string AmendFeeRuleCode { get; set; }
        public virtual string ProcessPartyStatusUpdateInd { get; set; }
        public virtual string ObsInd { get; set; }
        public virtual string LastModifiedBy { get; set; }
        public virtual DateTime LastModifiedDate { get; set; }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            MDocControlForum toCompareWith = obj as MDocControlForum;
            return toCompareWith == null ? false : ((this.DocControlId == toCompareWith.DocControlId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.DocControlId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}