#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MHRGBeforeType'</summary>
    public partial class MHRGBeforeType : IMaster
    {
        #region Fields

        private System.String _description;
        private System.String _feeRuleCode;
        private System.String _forumId;
        private System.Collections.Generic.ICollection<Hearing> _hearings;
        private System.Collections.Generic.ICollection<Hearing> _hearingsEstimatedHRGBeforeTypeCode;
        private System.String _hRGBeforeTypeCode;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;

        //private MFilingFee _mFilingFee;
        //private MForumType _mForumType;
        private System.String _obsInd;
        private System.Collections.Generic.ICollection<PaymentHRGDatesDocDetail> _paymentHRGDatesDocDetails;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MHRGBeforeType"/> class.</summary>
        public MHRGBeforeType()
            : base()
        {
            _hearingsEstimatedHRGBeforeTypeCode = new System.Collections.Generic.HashSet<Hearing>();
            _hearings = new System.Collections.Generic.HashSet<Hearing>();
            _paymentHRGDatesDocDetails = new System.Collections.Generic.HashSet<PaymentHRGDatesDocDetail>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the Description field. </summary>
        public virtual System.String Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>Gets or sets the FeeRuleCode field. </summary>
        public virtual System.String FeeRuleCode
        {
            get { return _feeRuleCode; }
            set { _feeRuleCode = value; }
        }

        /// <summary>Gets or sets the ForumId field. </summary>
        public virtual System.String ForumId
        {
            get { return _forumId; }
            set { _forumId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Case.Hearing.MHRGBeforeType - Master.MHRGBeforeType.Hearings (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<Hearing> Hearings
        {
            get { return _hearings; }
            set { _hearings = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Case.Hearing.MHRGBeforeTypeEstimatedHRGBeforeTypeCode - Master.MHRGBeforeType.HearingsEstimatedHRGBeforeTypeCode (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<Hearing> HearingsEstimatedHRGBeforeTypeCode
        {
            get { return _hearingsEstimatedHRGBeforeTypeCode; }
            set { _hearingsEstimatedHRGBeforeTypeCode = value; }
        }

        /// <summary>Gets or sets the HRGBeforeTypeCode field. </summary>
        public virtual System.String HRGBeforeTypeCode
        {
            get { return _hRGBeforeTypeCode; }
            set { _hRGBeforeTypeCode = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MHRGBeforeType.MFilingFee - Master.MFilingFee.MHRGBeforeTypes (m:1)'</summary>
        //public virtual MFilingFee MFilingFee
        //{
        //    get { return _mFilingFee; }
        //    set { _mFilingFee = value; }
        //}
        /// <summary>Represents the navigator which is mapped onto the association 'Master.MHRGBeforeType.MForumType - Master.MForumType.MHRGBeforeTypes (m:1)'</summary>
        //public virtual MForumType MForumType
        //{
        //    get { return _mForumType; }
        //    set { _mForumType = value; }
        //}
        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.PaymentHRGDatesDocDetail.MHRGBeforeType - Master.MHRGBeforeType.PaymentHRGDatesDocDetails (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<PaymentHRGDatesDocDetail> PaymentHRGDatesDocDetails
        {
            get { return _paymentHRGDatesDocDetails; }
            set { _paymentHRGDatesDocDetails = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MHRGBeforeType toCompareWith = obj as MHRGBeforeType;
            return toCompareWith == null ? false : ((this.HRGBeforeTypeCode == toCompareWith.HRGBeforeTypeCode));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.HRGBeforeTypeCode.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}