#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MinuteSheet'</summary>
    public partial class MinuteSheetPartyRepInfo : ICommon
    {
        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MinuteSheet"/> class.</summary>
        public MinuteSheetPartyRepInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CaseInfoId field. </summary>
        public virtual String CasePartyId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get;
            set;
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get;
            set;
        }

        /// <summary>Gets or sets the AttachmentDocId field. </summary>
        public virtual String MinuteSheetInfoId
        {
            get ;
            set;
        }

        /// <summary>Gets or sets the ApprovedBy field. </summary>
        public virtual String MinuteSheetPartyRepInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CreatedBy field. </summary>
        public virtual String PartyRepresentationType
        {
            get ;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MinuteSheetPartyRepInfo toCompareWith = obj as MinuteSheetPartyRepInfo;
            return toCompareWith == null ? false : ((this.MinuteSheetPartyRepInfoId == toCompareWith.MinuteSheetPartyRepInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.MinuteSheetPartyRepInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}