#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MRulesOfCourtOrder'</summary>
    public partial class MRulesOfCourtOrder : IMaster
    {
        #region Fields

        private System.Decimal _amount;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MForumType _mForumType;
        private System.String _obsInd;
        private System.String _orderNo;
        private System.String _paymentInReason;
        private System.String _ruleNo;
        private System.String _ruleOrderCode;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MRulesOfCourtOrder"/> class.</summary>
        public MRulesOfCourtOrder()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the Amount field. </summary>
        public virtual System.Decimal Amount
        {
            get { return _amount; }
            set { _amount = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MRulesOfCourtOrder.MForumType - Master.MForumType.MRulesOfCourtOrders (m:1)'</summary>
        public virtual MForumType MForumType
        {
            get { return _mForumType; }
            set { _mForumType = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the OrderNo field. </summary>
        public virtual System.String OrderNo
        {
            get { return _orderNo; }
            set { _orderNo = value; }
        }

        /// <summary>Gets or sets the PaymentInReason field. </summary>
        public virtual System.String PaymentInReason
        {
            get { return _paymentInReason; }
            set { _paymentInReason = value; }
        }

        /// <summary>Gets or sets the RuleNo field. </summary>
        public virtual System.String RuleNo
        {
            get { return _ruleNo; }
            set { _ruleNo = value; }
        }

        /// <summary>Gets or sets the RuleOrderCode field. </summary>
        public virtual System.String RuleOrderCode
        {
            get { return _ruleOrderCode; }
            set { _ruleOrderCode = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MRulesOfCourtOrder toCompareWith = obj as MRulesOfCourtOrder;
            return toCompareWith == null ? false : ((this.RuleOrderCode == toCompareWith.RuleOrderCode));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.RuleOrderCode.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}