#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.NatureOfCase'</summary>
    public partial class NatureOfCase : ICommon
    {
        #region Fields

        //private CaseInfo _caseInfo;
        private Nullable<System.Int64> _caseInfoId;
        private System.Decimal _itemNo;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _mainNOCInd;
        private MNOC _mNOC;
        private System.String _natureOfCaseId;
        private System.String _obsInd;
        private System.String _otherText;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="NatureOfCase"/> class.</summary>
        public NatureOfCase()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Common.NatureOfCase.CaseInfo - Case.CaseInfo.NatureOfCases (m:1)'</summary>
        //public virtual CaseInfo CaseInfo
        //{
        //    get { return _caseInfo; }
        //    set { _caseInfo = value; }
        //}
        public virtual Nullable<System.Int64> CaseInfoId
        {
            get { return _caseInfoId; }
            set { _caseInfoId = value; }
        }

        /// <summary>Gets or sets the ItemNo field. </summary>
        public virtual System.Decimal ItemNo
        {
            get { return _itemNo; }
            set { _itemNo = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MainNOCInd field. </summary>
        public virtual System.String MainNOCInd
        {
            get { return _mainNOCInd; }
            set { _mainNOCInd = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.NatureOfCase.MNOC - Master.MNOC.NatureOfCases (m:1)'</summary>
        public virtual MNOC MNOC
        {
            get { return _mNOC; }
            set { _mNOC = value; }
        }

        /// <summary>Gets or sets the NatureOfCaseId field. </summary>
        public virtual System.String NatureOfCaseId
        {
            get { return _natureOfCaseId; }
            set { _natureOfCaseId = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the OtherText field. </summary>
        public virtual System.String OtherText
        {
            get { return _otherText; }
            set { _otherText = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            NatureOfCase toCompareWith = obj as NatureOfCase;
            return toCompareWith == null ? false : ((this.NatureOfCaseId == toCompareWith.NatureOfCaseId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.NatureOfCaseId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}