#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.OtherReliefsClaim'</summary>
    public partial class OtherReliefsClaim : ICommon
    {
        #region Fields

        private Nullable<System.Int64> _itemNo;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MRelief _mRelief;
        private System.String _otherReliefsClaimId;
        private System.String _reliefRemarks;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="OtherReliefsClaim"/> class.</summary>
        public OtherReliefsClaim()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the ItemNo field. </summary>
        public virtual Nullable<System.Int64> ItemNo
        {
            get { return _itemNo; }
            set { _itemNo = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.OtherReliefsClaim.MRelief - Master.MRelief.OtherReliefsClaims (m:1)'</summary>
        public virtual MRelief MRelief
        {
            get { return _mRelief; }
            set { _mRelief = value; }
        }

        /// <summary>Gets or sets the OtherReliefsClaimId field. </summary>
        public virtual System.String OtherReliefsClaimId
        {
            get { return _otherReliefsClaimId; }
            set { _otherReliefsClaimId = value; }
        }

        /// <summary>Gets or sets the ReliefRemarks field. </summary>
        public virtual System.String ReliefRemarks
        {
            get { return _reliefRemarks; }
            set { _reliefRemarks = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            OtherReliefsClaim toCompareWith = obj as OtherReliefsClaim;
            return toCompareWith == null ? false : ((this.OtherReliefsClaimId == toCompareWith.OtherReliefsClaimId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.OtherReliefsClaimId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}