#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;

    /// <summary>Class which represents the entity 'Case.PartyCaseFileRefNumber'</summary>
    public partial class PartyCaseFileRefNumber : ICase
    {


        /// <summary> /// Initializes a new instance of the <see cref="PartyCaseFileRefNumber"/> class./// </summary>
        public PartyCaseFileRefNumber()
            : base()
        {

        }

        #region Properties

        public virtual string PartyCaseFileRefNumberId { get; set; }
        public virtual long? CaseInfoID { get; set; }
        public virtual string CasePartyID { get; set; }
        public virtual string LFFileRefNumber { get; set; }
        public virtual string ObsInd { get; set; }
        public virtual string LastModifiedBy { get; set; }
        public virtual DateTime LastModifiedDate { get; set; }
        public virtual string LFID { get; set; }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            PartyCaseFileRefNumber toCompareWith = obj as PartyCaseFileRefNumber;
            return toCompareWith == null ? false : ((this.PartyCaseFileRefNumberId == toCompareWith.PartyCaseFileRefNumberId) && (this.CaseInfoID == toCompareWith.CaseInfoID));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CaseInfoID.GetHashCode();
            toReturn ^= this.PartyCaseFileRefNumberId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}