#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.PCAppDetailsFromLawSoc'</summary>
    public partial class PCAppDetailsFromLawSoc
    {
        #region Fields

        private System.String _annualSubPaidStatus;
        private CaseInfo _caseInfo;
        private System.String _compFundStatus;
        private Nullable<System.DateTime> _insurnCvrgEndDate;
        private Nullable<System.DateTime> _insurnCvrgStartDate;
        private System.String _isExternalAgencyUserApproved;
        private System.String _isSavedInPCInfo;
        private System.String _keyFromLawSoc;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _membershipCategory;
        private System.String _pCAppDetailsFromLawSocId;
        private SubCaseInfo _subCaseInfo;
        private System.String _voteInfo;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="PCAppDetailsFromLawSoc"/> class.</summary>
        public PCAppDetailsFromLawSoc()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

       
        /// <summary>Represents the navigator which is mapped onto the association 'Common.PCAppDetailsFromLawSoc.CaseInfo - Case.CaseInfo.PCAppDetailsFromLawSocs (m:1)'</summary>
        public virtual CaseInfo CaseInfo
        {
            get { return _caseInfo; }
            set { _caseInfo = value; }
        }

       

       

        /// <summary>Gets or sets the KeyFromLawSoc field. </summary>
        public virtual System.String KeyFromLawSoc
        {
            get { return _keyFromLawSoc; }
            set { _keyFromLawSoc = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MembershipCategory field. </summary>
        public virtual System.String MembershipCategory
        {
            get { return _membershipCategory; }
            set { _membershipCategory = value; }
        }

        /// <summary>Gets or sets the PCAppDetailsFromLawSocId field. </summary>
        public virtual System.String PCAppDetailsFromLawSocId
        {
            get { return _pCAppDetailsFromLawSocId; }
            set { _pCAppDetailsFromLawSocId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.PCAppDetailsFromLawSoc.SubCaseInfo - SubCase.SubCaseInfo.PCAppDetailsFromLawSocs (m:1)'</summary>
        public virtual SubCaseInfo SubCaseInfo
        {
            get { return _subCaseInfo; }
            set { _subCaseInfo = value; }
        }

        /// <summary>Gets or sets the VoteInfo field. </summary>
        public virtual System.String VoteInfo
        {
            get { return _voteInfo; }
            set { _voteInfo = value; }
        }

        public virtual string SubscriptionFee { get; set; }

        public virtual string PCInfo
        {
            get;
            set;
        }

        public virtual decimal? PCCaseYear
        {
            get;
            set;
        }

        public virtual string ObsInd
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            PCAppDetailsFromLawSoc toCompareWith = obj as PCAppDetailsFromLawSoc;
            return toCompareWith == null ? false : ((this.PCAppDetailsFromLawSocId == toCompareWith.PCAppDetailsFromLawSocId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.PCAppDetailsFromLawSocId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}