#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'SubCaseSpecific.PCInfo'</summary>
    public partial class PCInfo : ISubCaseSpecific 
    {
        #region Fields

        private System.String _anyAdvrOrdersInForeignJuri;
        private System.String _circumstancesAndJurisdictions;
        private Nullable<System.DateTime> _commOfOathsAppDate;
        private Nullable<System.DateTime> _commOfOathsAppExpDate;
        private System.String _countriesQualifiedForPractice;
        private Nullable<System.DateTime> _dateOfAGCCertIssued;
        private System.String _doesPracticeIncludeLitigation;
        private System.String _finalConfirmation;
        private System.String _hasSection251bSatisfied;
        private System.String _hasSection251cSatisfied;
        private System.String _hasSection251dSatisfied;
        private System.String _iDoNotNeedToVote;
        private System.String _isAreaOfLPDisclosed;
        private System.String _isConditionalPC;
        private System.String _isDisqualifiedBySection261;
        private System.String _isDisqualifiedBySection262;
        private System.String _isDisqualifiedBySection263;
        private System.String _isNotHoldClientMoney;
        private System.String _isNotPeriodOfFiveYears;
        private System.String _isOnRollOfAdvsSolicitors;
        private System.String _isPCPossessedLPA261;
        private System.String _isPeriodOfFiveYears;
        private System.String _isProfIndemnityInsur;
        private System.String _isSatisfiedSec130N;
        private System.String _isSection25AApplicable;
        private System.String _isVoted;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _lawSocAnnualSubPaidStatus;
        private System.String _lawSocCompFundStatus;
        private Nullable<System.DateTime> _lawSocInsurnCvrgEndDate;
        private Nullable<System.DateTime> _lawSocInsurnCvrgStartDate;
        private System.String _lawSocMembershipCategory;
        private System.String _lawSocVoteInfo;
        private System.String _legalOfficerExperience;
        private System.String _locumSolicitorPosition;
        private Nullable<System.DateTime> _nPAppDate;
        private Nullable<System.DateTime> _nPAppExpDate;
        private System.String _orgAccReportSection73OfLPA;
        private System.String _pCInfoId;
        private Nullable<System.Decimal> _proBonoHours;
        private System.String _proBonoInitiatives;
        private System.String _qualifiedForPractice;
        private System.String _sALfeePaidStatus;
        private Nullable<System.DateTime> _sCAppDate;
        private Nullable<System.DateTime> _sCAppExpDate;
        private System.String _section25AReason;
        private System.String _submissionGroupId;
        private System.String _subSectionForSection25A;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="PCInfo"/> class.</summary>
        public PCInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the AnyAdvrOrdersInForeignJuri field. </summary>
        public virtual System.String AnyAdvrOrdersInForeignJuri
        {
            get { return _anyAdvrOrdersInForeignJuri; }
            set { _anyAdvrOrdersInForeignJuri = value; }
        }

        public virtual String ApptLFId
        {
            get;
            set;
        }

        public virtual String ApptOrgType
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CircumstancesAndJurisdictions field. </summary>
        public virtual System.String CircumstancesAndJurisdictions
        {
            get { return _circumstancesAndJurisdictions; }
            set { _circumstancesAndJurisdictions = value; }
        }

        /// <summary>Gets or sets the CommOfOathsAppDate field. </summary>
        public virtual Nullable<System.DateTime> CommOfOathsAppDate
        {
            get { return _commOfOathsAppDate; }
            set { _commOfOathsAppDate = value; }
        }

        /// <summary>Gets or sets the CommOfOathsAppExpDate field. </summary>
        public virtual Nullable<System.DateTime> CommOfOathsAppExpDate
        {
            get { return _commOfOathsAppExpDate; }
            set { _commOfOathsAppExpDate = value; }
        }

        /// <summary>Gets or sets the CountriesQualifiedForPractice field. </summary>
        public virtual System.String CountriesQualifiedForPractice
        {
            get { return _countriesQualifiedForPractice; }
            set { _countriesQualifiedForPractice = value; }
        }

        /// <summary>Gets or sets the DateOfAGCCertIssued field. </summary>
        public virtual Nullable<System.DateTime> DateOfAGCCertIssued
        {
            get { return _dateOfAGCCertIssued; }
            set { _dateOfAGCCertIssued = value; }
        }

        /// <summary>Gets or sets the DoesPracticeIncludeLitigation field. </summary>
        public virtual System.String DoesPracticeIncludeLitigation
        {
            get { return _doesPracticeIncludeLitigation; }
            set { _doesPracticeIncludeLitigation = value; }
        }

        /// <summary>Gets or sets the FinalConfirmation field. </summary>
        public virtual System.String FinalConfirmation
        {
            get { return _finalConfirmation; }
            set { _finalConfirmation = value; }
        }

        /// <summary>Gets or sets the HasSection251bSatisfied field. </summary>
        public virtual System.String HasSection251bSatisfied
        {
            get { return _hasSection251bSatisfied; }
            set { _hasSection251bSatisfied = value; }
        }

        /// <summary>Gets or sets the HasSection251cSatisfied field. </summary>
        public virtual System.String HasSection251cSatisfied
        {
            get { return _hasSection251cSatisfied; }
            set { _hasSection251cSatisfied = value; }
        }

        /// <summary>Gets or sets the HasSection251dSatisfied field. </summary>
        public virtual System.String HasSection251dSatisfied
        {
            get { return _hasSection251dSatisfied; }
            set { _hasSection251dSatisfied = value; }
        }

        /// <summary>Gets or sets the IDoNotNeedToVote field. </summary>
        public virtual System.String IDoNotNeedToVote
        {
            get { return _iDoNotNeedToVote; }
            set { _iDoNotNeedToVote = value; }
        }

        /// <summary>Gets or sets the IsAreaOfLPDisclosed field. </summary>
        public virtual System.String IsAreaOfLPDisclosed
        {
            get { return _isAreaOfLPDisclosed; }
            set { _isAreaOfLPDisclosed = value; }
        }

        /// <summary>Gets or sets the IsConditionalPC field. </summary>
        public virtual System.String IsConditionalPC
        {
            get { return _isConditionalPC; }
            set { _isConditionalPC = value; }
        }

        /// <summary>Gets or sets the IsDisqualifiedBySection261 field. </summary>
        public virtual System.String IsDisqualifiedBySection261
        {
            get { return _isDisqualifiedBySection261; }
            set { _isDisqualifiedBySection261 = value; }
        }

        /// <summary>Gets or sets the IsDisqualifiedBySection262 field. </summary>
        public virtual System.String IsDisqualifiedBySection262
        {
            get { return _isDisqualifiedBySection262; }
            set { _isDisqualifiedBySection262 = value; }
        }

        /// <summary>Gets or sets the IsDisqualifiedBySection263 field. </summary>
        public virtual System.String IsDisqualifiedBySection263
        {
            get { return _isDisqualifiedBySection263; }
            set { _isDisqualifiedBySection263 = value; }
        }

        /// <summary>Gets or sets the IsNotHoldClientMoney field. </summary>
        public virtual System.String IsNotHoldClientMoney
        {
            get { return _isNotHoldClientMoney; }
            set { _isNotHoldClientMoney = value; }
        }

        /// <summary>Gets or sets the IsNotPeriodOfFiveYears field. </summary>
        public virtual System.String IsNotPeriodOfFiveYears
        {
            get { return _isNotPeriodOfFiveYears; }
            set { _isNotPeriodOfFiveYears = value; }
        }

        /// <summary>Gets or sets the IsOnRollOfAdvsSolicitors field. </summary>
        public virtual System.String IsOnRollOfAdvsSolicitors
        {
            get { return _isOnRollOfAdvsSolicitors; }
            set { _isOnRollOfAdvsSolicitors = value; }
        }

        /// <summary>Gets or sets the IsPCPossessedLPA261 field. </summary>
        public virtual System.String IsPCPossessedLPA261
        {
            get { return _isPCPossessedLPA261; }
            set { _isPCPossessedLPA261 = value; }
        }

        /// <summary>Gets or sets the IsPeriodOfFiveYears field. </summary>
        public virtual System.String IsPeriodOfFiveYears
        {
            get { return _isPeriodOfFiveYears; }
            set { _isPeriodOfFiveYears = value; }
        }

        /// <summary>Gets or sets the IsProfIndemnityInsur field. </summary>
        public virtual System.String IsProfIndemnityInsur
        {
            get { return _isProfIndemnityInsur; }
            set { _isProfIndemnityInsur = value; }
        }

        /// <summary>Gets or sets the IsRequiredVote field. </summary>
        public virtual String IsRequiredVote
        {
            get;
            set;
        }

        /// <summary>Gets or sets the IsSatisfiedSec130N field. </summary>
        public virtual System.String IsSatisfiedSec130N
        {
            get { return _isSatisfiedSec130N; }
            set { _isSatisfiedSec130N = value; }
        }

        /// <summary>Gets or sets the IsSection25AApplicable field. </summary>
        public virtual System.String IsSection25AApplicable
        {
            get { return _isSection25AApplicable; }
            set { _isSection25AApplicable = value; }
        }

        /// <summary>Gets or sets the IsVoted field. </summary>
        public virtual System.String IsVoted
        {
            get { return _isVoted; }
            set { _isVoted = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the LawSocAnnualSubPaidStatus field. </summary>
        public virtual System.String LawSocAnnualSubPaidStatus
        {
            get { return _lawSocAnnualSubPaidStatus; }
            set { _lawSocAnnualSubPaidStatus = value; }
        }

        /// <summary>Gets or sets the LawSocCompFundStatus field. </summary>
        public virtual System.String LawSocCompFundStatus
        {
            get { return _lawSocCompFundStatus; }
            set { _lawSocCompFundStatus = value; }
        }

        /// <summary>Gets or sets the LawSocInsurnCvrgEndDate field. </summary>
        public virtual Nullable<System.DateTime> LawSocInsurnCvrgEndDate
        {
            get { return _lawSocInsurnCvrgEndDate; }
            set { _lawSocInsurnCvrgEndDate = value; }
        }

        /// <summary>Gets or sets the LawSocInsurnCvrgStartDate field. </summary>
        public virtual Nullable<System.DateTime> LawSocInsurnCvrgStartDate
        {
            get { return _lawSocInsurnCvrgStartDate; }
            set { _lawSocInsurnCvrgStartDate = value; }
        }

        /// <summary>Gets or sets the LawSocMembershipCategory field. </summary>
        public virtual System.String LawSocMembershipCategory
        {
            get { return _lawSocMembershipCategory; }
            set { _lawSocMembershipCategory = value; }
        }

        /// <summary>Gets or sets the LawSocVoteInfo field. </summary>
        public virtual System.String LawSocVoteInfo
        {
            get { return _lawSocVoteInfo; }
            set { _lawSocVoteInfo = value; }
        }

        /// <summary>Gets or sets the LegalOfficerExperience field. </summary>
        public virtual System.String LegalOfficerExperience
        {
            get { return _legalOfficerExperience; }
            set { _legalOfficerExperience = value; }
        }

        /// <summary>Gets or sets the LocumSolicitorPosition field. </summary>
        public virtual System.String LocumSolicitorPosition
        {
            get { return _locumSolicitorPosition; }
            set { _locumSolicitorPosition = value; }
        }

        public virtual MApptOrganisation MApptOrganisation
        {
            get;
            set;
        }

        /// <summary>Gets or sets the NPAppDate field. </summary>
        public virtual Nullable<System.DateTime> NPAppDate
        {
            get { return _nPAppDate; }
            set { _nPAppDate = value; }
        }

        /// <summary>Gets or sets the NPAppExpDate field. </summary>
        public virtual Nullable<System.DateTime> NPAppExpDate
        {
            get { return _nPAppExpDate; }
            set { _nPAppExpDate = value; }
        }

        /// <summary>Gets or sets the OrgAccReportSection73OfLPA field. </summary>
        public virtual System.String OrgAccReportSection73OfLPA
        {
            get { return _orgAccReportSection73OfLPA; }
            set { _orgAccReportSection73OfLPA = value; }
        }

        /// <summary>Gets or sets the PCInfoId field. </summary>
        public virtual System.String PCInfoId
        {
            get { return _pCInfoId; }
            set { _pCInfoId = value; }
        }

        /// <summary>Gets or sets the ProBonoHours field. </summary>
        public virtual Nullable<System.Decimal> ProBonoHours
        {
            get { return _proBonoHours; }
            set { _proBonoHours = value; }
        }

        /// <summary>Gets or sets the ProBonoInitiatives field. </summary>
        public virtual System.String ProBonoInitiatives
        {
            get { return _proBonoInitiatives; }
            set { _proBonoInitiatives = value; }
        }

        /// <summary>Gets or sets the QualifiedForPractice field. </summary>
        public virtual System.String QualifiedForPractice
        {
            get { return _qualifiedForPractice; }
            set { _qualifiedForPractice = value; }
        }

        /// <summary>Gets or sets the SALfeePaidStatus field. </summary>
        public virtual System.String SALfeePaidStatus
        {
            get { return _sALfeePaidStatus; }
            set { _sALfeePaidStatus = value; }
        }

        /// <summary>Gets or sets the SALMembership field. </summary>
        public virtual System.String SALMembership
        {
            get;
            set;
        }

        /// <summary>Gets or sets the SCAppDate field. </summary>
        public virtual Nullable<System.DateTime> SCAppDate
        {
            get { return _sCAppDate; }
            set { _sCAppDate = value; }
        }

        /// <summary>Gets or sets the SCAppExpDate field. </summary>
        public virtual Nullable<System.DateTime> SCAppExpDate
        {
            get { return _sCAppExpDate; }
            set { _sCAppExpDate = value; }
        }

        /// <summary>Gets or sets the Section25AReason field. </summary>
        public virtual System.String Section25AReason
        {
            get { return _section25AReason; }
            set { _section25AReason = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        /// <summary>Gets or sets the SubSectionForSection25A field. </summary>
        public virtual System.String SubSectionForSection25A
        {
            get { return _subSectionForSection25A; }
            set { _subSectionForSection25A = value; }
        }

        public virtual decimal? LawsoSubscriptionFee { get; set; }

        public virtual decimal? LawsoCompensationFee { get; set; }

        public virtual decimal? LawsoVotePenalityFee { get; set; }

        public virtual decimal? SALFee { get; set; }

        public virtual string CORDocId { get; set; }

        public virtual decimal? PCCaseYear
        {
            get;
            set;
        }

        public virtual decimal? ProBonoStateHours
        {
            get;
            set;
        }

        public virtual string PbnoTrg
        {
            get;
            set;
        }

        public virtual string PbnoMentor
        {
            get;
            set;
        }

        public virtual string PbnoScheme
        {
            get;
            set;
        }

        public virtual string PbnoBillableHrs
        {
            get;
            set;
        }

        public virtual string PbnoencOthers
        {
            get;
            set;
        }

        public virtual string PbnoencOthersremarks
        {
            get;
            set;
        }

        public virtual string PbnoOppurtunity
        {
            get;
            set;
        }

        public virtual string PbnoQualified
        {
            get;
            set;
        }

        public virtual string PbnoNotime
        {
            get;
            set;
        }

        public virtual string PbnoLegalPractice
        {
            get;
            set;
        }

        public virtual string PbnoHighbillable
        {
            get;
            set;
        }

        public virtual string PbnoMoreothers
        {
            get;
            set;
        }

        public virtual string PbnoMorehrsOthers
        {
            get;
            set;
        }

        public virtual string PbnoLegalservices
        {
            get;
            set;
        }

        public virtual decimal? PbnoDonations
        {
            get;
            set;
        }

        public virtual string Pbnochq
        {
            get;
            set;
        }

        public virtual string PbnoLawsoc
        {
            get;
            set;
        }


        public virtual string CPDReq
        {
            get;
            set;
        }

        public virtual string Sec73LPA
        {
            get;
            set;
        }

        public virtual string Sec73Trivual
        {
            get;
            set;
        }

        public virtual string Sec731stSection
        {
            get;
            set;
        }

        public virtual string Sec732ndSection
        {
            get;
            set;
        }

        public virtual string AccRep41f
        {
            get;
            set;
        }

        public virtual string LSGIRORPTST
        {
            get;
            set;
        }

        public virtual string LSHCRPTST
        {
            get;
            set;
        }
        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            PCInfo toCompareWith = obj as PCInfo;
            return toCompareWith == null ? false : ((this.PCInfoId == toCompareWith.PCInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.PCInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}