#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Case.RLawFirmSolicitors'</summary>
    public partial class RLawFirmSolicitorHistory : ICase
    {
     
        #region Properties

        public virtual string  LFID { get; set; }

        public virtual  long  SolicitorId { get; set; }

        public virtual DateTime StartDate { get; set; }

        public virtual DateTime? EndDate { get; set; }

        public virtual DateTime LastModifiedDate{ get; set; }

        public virtual string LastModifiedBy { get; set; }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            RLawFirmSolicitorHistory toCompareWith = obj as RLawFirmSolicitorHistory;
            return toCompareWith == null ? false : ((this.LFID == toCompareWith.LFID) 
                && (this.SolicitorId == toCompareWith.SolicitorId)
                && (this.StartDate == toCompareWith.StartDate));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.LFID.GetHashCode();
            toReturn ^= this.SolicitorId.GetHashCode();
            toReturn ^= this.StartDate.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}