#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.RMHRGTypeHRGSlot'</summary>
    public partial class RMHRGTypeHRGSlot:IMaster
    {
        #region Fields

        private System.String _courtInd;
        private System.String _hRGSlotCode;
        private System.String _hRGTypeCode;
        private System.String _isInterfaced;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _obsInd;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="RMHRGTypeHRGSlot"/> class.</summary>
        public RMHRGTypeHRGSlot()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CourtInd field. </summary>
        public virtual System.String CourtInd
        {
            get { return _courtInd; }
            set { _courtInd = value; }
        }

        /// <summary>Gets or sets the HRGSlotCode field. </summary>
        public virtual System.String HRGSlotCode
        {
            get { return _hRGSlotCode; }
            set { _hRGSlotCode = value; }
        }

        /// <summary>Gets or sets the HRGTypeCode field. </summary>
        public virtual System.String HRGTypeCode
        {
            get { return _hRGTypeCode; }
            set { _hRGTypeCode = value; }
        }

        /// <summary>Gets or sets the IsInterfaced field. </summary>
        public virtual System.String IsInterfaced
        {
            get { return _isInterfaced; }
            set { _isInterfaced = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            RMHRGTypeHRGSlot toCompareWith = obj as RMHRGTypeHRGSlot;
            return toCompareWith == null ? false : ((this.CourtInd == toCompareWith.CourtInd) && (this.HRGSlotCode == toCompareWith.HRGSlotCode) && (this.HRGTypeCode == toCompareWith.HRGTypeCode));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CourtInd.GetHashCode();
            toReturn ^= this.HRGSlotCode.GetHashCode();
            toReturn ^= this.HRGTypeCode.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}