#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.SubmissionInfo'</summary>
    public partial class SubmissionInfo : ICommon
    {
        #region Fields

        private System.String _accountId;
        private System.String _eTA;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _submissionGroupId;
        private System.String _submissionNumber;
        private System.String _accountIdToCharge;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="SubmissionInfo"/> class.</summary>
        public SubmissionInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the AccountId field. </summary>
        public virtual System.String AccountId
        {
            get { return _accountId; }
            set { _accountId = value; }
        }

        /// <summary>Gets or sets the ETA field. </summary>
        public virtual System.String ETA
        {
            get { return _eTA; }
            set { _eTA = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.SubmissionInfo.LawFirm - Common.LawFirm.SubmissionInfos (m:1)'</summary>
        //public virtual LawFirm LawFirm
        //{
        //    get { return _lawFirm; }
        //    set { _lawFirm = value; }
        //}
        /// <summary>Gets or sets the LFID field. </summary>
        public virtual System.String LFID
        {
            get;
            set;
        }

        /// <summary>Gets or sets the Stage field. </summary>
        public virtual System.String Stage
        {
            get;
            set;
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        /// <summary>Gets or sets the SubmissionNumber field. </summary>
        public virtual System.String SubmissionNumber
        {
            get { return _submissionNumber; }
            set { _submissionNumber = value; }
        }

        public virtual string IsCaseArchived
        {
            get;
            set;
        }

        public virtual string LFAccountIdToCharge
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            SubmissionInfo toCompareWith = obj as SubmissionInfo;
            return toCompareWith == null ? false : ((this.SubmissionGroupId == toCompareWith.SubmissionGroupId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.SubmissionGroupId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}