#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.UnliquidatedClaim'</summary>
    public partial class UnliquidatedClaim : ICommon
    {
        #region Fields

        private System.String _description;
        private Nullable<System.Int64> _itemNo;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _submissionGroupId;
        private System.String _unLIQClaimType;
        private System.String _unliquidatedClaimId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="UnliquidatedClaim"/> class.</summary>
        public UnliquidatedClaim()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the Description field. </summary>
        public virtual System.String Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>Gets or sets the ItemNo field. </summary>
        public virtual Nullable<System.Int64> ItemNo
        {
            get { return _itemNo; }
            set { _itemNo = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        /// <summary>Gets or sets the UnLIQClaimType field. </summary>
        public virtual System.String UnLIQClaimType
        {
            get { return _unLIQClaimType; }
            set { _unLIQClaimType = value; }
        }

        /// <summary>Gets or sets the UnliquidatedClaimId field. </summary>
        public virtual System.String UnliquidatedClaimId
        {
            get { return _unliquidatedClaimId; }
            set { _unliquidatedClaimId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            UnliquidatedClaim toCompareWith = obj as UnliquidatedClaim;
            return toCompareWith == null ? false : ((this.UnliquidatedClaimId == toCompareWith.UnliquidatedClaimId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.UnliquidatedClaimId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}