#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Common
{
    using System;

    using AllInOne.Legal.Domain.Abstract;
    using AllInOne.Legal.Domain.Case;
    using AllInOne.Legal.Domain.Interfaces;
    using AllInOne.Legal.Domain.LawFirm;
    using AllInOne.Legal.Domain.Master;

    /// <summary>Class which represents the entity 'Common.ForeignLPSolicitorRegDetailEntity'</summary>
    public class ForeignLPSolicitorRegDetailEntity : AbstractLastModified, ICommonEntity
    {
        #region Properties

        /// <summary>Gets or sets the ForeignLFID field. </summary>
        public String ForeignLFID
        {
            get;
            set;
        }

        public String ForeignLPSolicitorRegId
        {
            get;
            set;
        }

        public int ItemNo
        {
            get;
            set;
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.ForeignLPSolicitorReg.MTypeOfForeignLawPractice - Master.MTypeOfForeignLawPractice.ForeignLPSolicitorRegs (m:1)'</summary>
        public MTypeOfForeignLawPracticeEntity MTypeOfForeignLawPractice
        {
            get;
            set;
        }

        public MLawPracticeTypeEntity MLawPracticeType
        {
            get;
            set;
        }
        /// <summary>Gets or sets the SingaporeLFID field. </summary>
        public System.String SingaporeLFID
        {
            get;
            set;
        }

        public YesNo ObsInd { get; set; }
        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            ForeignLPSolicitorRegDetailEntity toCompareWith = obj as ForeignLPSolicitorRegDetailEntity;
            return toCompareWith == null ? false : ((this.ForeignLPSolicitorRegId == toCompareWith.ForeignLPSolicitorRegId) && (this.ItemNo == toCompareWith.ItemNo));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.ForeignLPSolicitorRegId.GetHashCode();
            toReturn ^= this.ItemNo.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}