namespace AllInOne.Legal.Domain.FrontEndSpecific{
	using System;
	using System.Collections.Generic;

	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public class VFilingLawFirmEntity
	{

		/// <summary>
		/// Gets or sets the DocID field.
		/// </summary>
		public System.String DocID
		{
			get; 
 			set; 
		}

		/// <summary>
		/// Gets or sets the FilingInd field.
		/// </summary>
		public System.String FilingInd
		{
			get; 
 			set; 
		}

		/// <summary>
		/// Gets or sets the OrganizationName field.
		/// </summary>
		public System.String OrganizationName
		{
			get; 
 			set; 
		}
#region ToString, Equals And HashCode Overrides
		/// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            VFilingLawFirmEntity toCompareWith = obj as VFilingLawFirmEntity;
			return toCompareWith == null ? false : ((this.DocID == toCompareWith.DocID));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.DocID.GetHashCode();
            return toReturn;
        }
		
		public override string ToString()
        {
			return 		"DocID=" + DocID + "--" + 
		"FilingInd=" + FilingInd + "--" + 
		"OrganizationName=" + OrganizationName + "--" + 
		"";
        }
		
		#endregion

	}
}
