#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Master
{
    using System;

    using AllInOne.Legal.Domain.Abstract;
    using AllInOne.Legal.Domain.Interfaces;

    /// <summary>Class which represents the entity 'Master.MEMSDisburseRate'</summary>
    [Serializable]
    public class MEMSDisburseRateEntity : AbstractMasterInfo, IMasterEntity
    {
        #region Properties

        /// <summary>Gets or sets the DayOfWeek field. </summary>
        public System.String DayOfWeek
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSDisburseRateCode field. </summary>
        public System.String EMSDisburseRateCode
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSType field. </summary>
        public EMSType EMSType
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EndTime field. </summary>
        public System.String EndTime
        {
            get;
            set;
        }

        /// <summary>Gets or sets the FrequencyInd field. </summary>
        public Nullable<System.Int32> FrequencyInd
        {
            get;
            set;
        }

        /// <summary>Gets or sets the Rate field. </summary>
        public Nullable<System.Decimal> Rate
        {
            get;
            set;
        }

        /// <summary>Gets or sets the StartTime field. </summary>
        public System.String StartTime
        {
            get;
            set;
        }

        /// <summary>Gets or sets the AppCode field. </summary>
        public System.String AppCode
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CourtId field. </summary>
        public System.String CourtId
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MEMSDisburseRateEntity toCompareWith = obj as MEMSDisburseRateEntity;
            return toCompareWith == null ? false : ((this.EMSDisburseRateCode == toCompareWith.EMSDisburseRateCode));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSDisburseRateCode.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}