#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Domain.Master
{
    using System;

    using AllInOne.Legal.Domain.Abstract;
    using AllInOne.Legal.Domain.Interfaces;

    /// <summary>
    /// Represents a standard domain entity for MEMSParamEntity.
    /// </summary>
    [Serializable]
    public class MEMSParamEntity : AbstractMasterInfo, IMasterEntity
    {
        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MEMSParamEntity"/> class.</summary>
        public MEMSParamEntity()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CategoryCode field. </summary>
        public System.String CategoryCode
        {
            get;
            set;
        }

        /// <summary>Gets or sets the EMSParamCode field. </summary>
        public System.String EMSParamCode
        {
            get;
            set;
        }

        /// <summary>Gets or sets the AppCode field. </summary>
        public System.String AppCode
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CourtId field. </summary>
        public System.String CourtId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the Value field. </summary>
        public System.String Value
        {
            get;
            set;
        }

        public YesNo IsAmendable { get; set; }
        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MEMSParamEntity toCompareWith = obj as MEMSParamEntity;
            return toCompareWith == null ? false : ((this.EMSParamCode == toCompareWith.EMSParamCode));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSParamCode.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}