#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Subsequent.ADMRSVCBBInfo'</summary>
    public partial class ADMRSVCBBInfo : ISubsequent
    {
        #region Fields

        private System.Collections.Generic.ICollection<ADMBBDefInfo> _aDMBBDefInfos;
        private System.Collections.Generic.ICollection<ADMBBSecInfo> _aDMBBSecInfos;
        private System.String _aDMRSVCBBInfoId;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _subjectAICId;
        private System.String _subjectDCPAICId;

        //private SubCaseInfo _subCaseInfo;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="ADMRSVCBBInfo"/> class.</summary>
        public ADMRSVCBBInfo()
            : base()
        {
            _aDMBBDefInfos = new System.Collections.Generic.HashSet<ADMBBDefInfo>();
            _aDMBBSecInfos = new System.Collections.Generic.HashSet<ADMBBSecInfo>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.ADMBBDefInfo.ADMRSVCBBInfo - Subsequent.ADMRSVCBBInfo.ADMBBDefInfos (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<ADMBBDefInfo> ADMBBDefInfos
        {
            get { return _aDMBBDefInfos; }
            set { _aDMBBDefInfos = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.ADMBBSecInfo.ADMRSVCBBInfo - Subsequent.ADMRSVCBBInfo.ADMBBSecInfos (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<ADMBBSecInfo> ADMBBSecInfos
        {
            get { return _aDMBBSecInfos; }
            set { _aDMBBSecInfos = value; }
        }

        /// <summary>Gets or sets the ADMRSVCBBInfoId field. </summary>
        public virtual System.String ADMRSVCBBInfoId
        {
            get { return _aDMRSVCBBInfoId; }
            set { _aDMRSVCBBInfoId = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.ADMRSVCBBInfo.SubCaseInfo - SubCase.SubCaseInfo.ADMRSVCBBInfos (m:1)'</summary>
        //public virtual SubCaseInfo SubCaseInfo
        //{
        //    get { return _subCaseInfo; }
        //    set { _subCaseInfo = value; }
        //}
        public virtual Int64? SubCaseInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the SubjectAICId field. </summary>
        public virtual System.String SubjectAICId
        {
            get { return _subjectAICId; }
            set { _subjectAICId = value; }
        }

        /// <summary>Gets or sets the SubjectDCPAICId field. </summary>
        public virtual System.String SubjectDCPAICId
        {
            get { return _subjectDCPAICId; }
            set { _subjectDCPAICId = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            ADMRSVCBBInfo toCompareWith = obj as ADMRSVCBBInfo;
            return toCompareWith == null ? false : ((this.ADMRSVCBBInfoId == toCompareWith.ADMRSVCBBInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.ADMRSVCBBInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}