#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'CaseSpecific.CaveatInfo'</summary>
    public partial class CaveatInfo:ICaseSpecific
    {
        #region Fields

        private CaseInfo _caseInfo;
        private System.String _caseNo;
        private System.String _caveatInfoId;
        private Nullable<System.DateTime> _caveatLapsedDate;
        private System.String _caveatType;
        private Nullable<System.DateTime> _caveatWithdrawnDate;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MForumType _mForumType;
        private SubCaseInfo _subCaseInfo;
        private System.String _submissionGroupId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="CaveatInfo"/> class.</summary>
        public CaveatInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'CaseSpecific.CaveatInfo.CaseInfo - Case.CaseInfo.CaveatInfos (m:1)'</summary>
        public virtual long CaseInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CaseNo field. </summary>
        public virtual System.String CaseNo
        {
            get { return _caseNo; }
            set { _caseNo = value; }
        }

        /// <summary>Gets or sets the CaveatInfoId field. </summary>
        public virtual System.String CaveatInfoId
        {
            get { return _caveatInfoId; }
            set { _caveatInfoId = value; }
        }

        /// <summary>Gets or sets the CaveatLapsedDate field. </summary>
        public virtual Nullable<System.DateTime> CaveatLapsedDate
        {
            get { return _caveatLapsedDate; }
            set { _caveatLapsedDate = value; }
        }

        /// <summary>Gets or sets the CaveatType field. </summary>
        public virtual System.String CaveatType
        {
            get { return _caveatType; }
            set { _caveatType = value; }
        }

        /// <summary>Gets or sets the CaveatWithdrawnDate field. </summary>
        public virtual Nullable<System.DateTime> CaveatWithdrawnDate
        {
            get { return _caveatWithdrawnDate; }
            set { _caveatWithdrawnDate = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'CaseSpecific.CaveatInfo.MForumType - Master.MForumType.CaveatInfos (m:1)'</summary>
        public virtual string ForumId
        {
            get;
            set;
        }

        /// <summary>Represents the navigator which is mapped onto the association 'CaseSpecific.CaveatInfo.SubCaseInfo - SubCase.SubCaseInfo.CaveatInfos (m:1)'</summary>
        public virtual long? SubCaseInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            CaveatInfo toCompareWith = obj as CaveatInfo;
            return toCompareWith == null ? false : ((this.CaveatInfoId == toCompareWith.CaveatInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CaveatInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}