#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.CheckListInstance'</summary>
    public partial class CheckListInstance : ICommon
    {
        #region Fields

        //private CaseInfo _caseInfo;
        private System.String _checkListInstanceId;
        private System.Collections.Generic.ICollection<CheckListSubmission> _checkListSubmissions;
        private Nullable<System.DateTime> _createDate;
        private Nullable<System.Int32> _currentStage;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MChecklist _mChecklist;
        private System.String _obsInd;
        private System.String _processedBy;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="CheckListInstance"/> class.</summary>
        public CheckListInstance()
            : base()
        {
            _checkListSubmissions = new System.Collections.Generic.HashSet<CheckListSubmission>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Common.ChecklistInstance.CaseInfo - Case.CaseInfo.ChecklistInstances (m:1)'</summary>
        //public virtual CaseInfo CaseInfo
        //{
        //    get { return _caseInfo; }
        //    set { _caseInfo = value; }
        //}
        /// <summary>
        /// Gets or sets the CaseInfoId field.
        /// </summary>
        public virtual Int64 CaseInfoId
        {
            get;
            set;
        }

        /// <summary>Gets or sets the CheckListInstanceId field. </summary>
        public virtual System.String CheckListInstanceId
        {
            get { return _checkListInstanceId; }
            set { _checkListInstanceId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.CheckListSubmission.CheckListInstance - Common.CheckListInstance.CheckListSubmissions (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<CheckListSubmission> CheckListSubmissions
        {
            get { return _checkListSubmissions; }
            set { _checkListSubmissions = value; }
        }

        /// <summary>Gets or sets the CreateDate field. </summary>
        public virtual Nullable<System.DateTime> CreateDate
        {
            get { return _createDate; }
            set { _createDate = value; }
        }

        /// <summary>Gets or sets the CurrentStage field. </summary>
        public virtual Nullable<System.Int32> CurrentStage
        {
            get { return _currentStage; }
            set { _currentStage = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.CheckListInstance.MChecklist - Master.MChecklist.CheckListInstances (m:1)'</summary>
        public virtual MChecklist MChecklist
        {
            get { return _mChecklist; }
            set { _mChecklist = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the ProcessedBy field. </summary>
        public virtual System.String ProcessedBy
        {
            get { return _processedBy; }
            set { _processedBy = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            CheckListInstance toCompareWith = obj as CheckListInstance;
            return toCompareWith == null ? false : ((this.CheckListInstanceId == toCompareWith.CheckListInstanceId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CheckListInstanceId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}