#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Enforcement.EMSAdmCharges'</summary>
    public partial class EMSAdmCharges : IEnforcement
    {
        #region Fields

        private EMSPaymentVoucher _eMSPaymentVoucher;
        private EMSAccount _eMSAccount;
        private EMSSale _eMSSale;
        private System.String _eMSAdmChargesId;
        private System.Decimal _amount;
        private System.String _chargesType;
        private System.String _isCharged;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _obsInd;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="EMSAdmCharges"/> class.</summary>
        public EMSAdmCharges()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the EMSPaymentVoucher field. </summary>
        public virtual EMSPaymentVoucher EMSPaymentVoucher
        {
            get { return _eMSPaymentVoucher; }
            set { _eMSPaymentVoucher = value; }
        }
        
        /// <summary>Gets or sets the EMSAccount field. </summary>
        public virtual EMSAccount EMSAccount
        {
            get { return _eMSAccount; }
            set { _eMSAccount = value; }
        }

        /// <summary>Gets or sets the EMSSale field. </summary>
        public virtual EMSSale EMSSale
        {
            get { return _eMSSale; }
            set { _eMSSale = value; }
        }

        /// <summary>Gets or sets the EMSAdmChargesId field. </summary>
        public virtual System.String EMSAdmChargesId
        {
            get { return _eMSAdmChargesId; }
            set { _eMSAdmChargesId = value; }
        }

        /// <summary>Gets or sets the Amount field. </summary>
        public virtual System.Decimal Amount
        {
            get { return _amount; }
            set { _amount = value; }
        }

        /// <summary>Gets or sets the ChargesType field. </summary>
        public virtual System.String ChargesType
        {
            get { return _chargesType; }
            set { _chargesType = value; }
        }

        /// <summary>Gets or sets the IsCharged field. </summary>
        public virtual System.String IsCharged
        {
            get { return _isCharged; }
            set { _isCharged = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            EMSAdmCharges toCompareWith = obj as EMSAdmCharges;
            return toCompareWith == null ? false : ((this.EMSAdmChargesId == toCompareWith.EMSAdmChargesId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSAdmChargesId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}