#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;

    /// <summary>Class which represents the entity 'Enforcement.EMSRecAudit'</summary>
    public partial class EMSRecAudit : IEnforcement
    {
        #region Fields

        private System.String _auditType;
        private System.String _eMSRecAuditId;
        private EMSReceipt _eMSReceipt;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _remarks;
        private System.String _reprintType;
        private System.String _voidReason;

        #endregion Fields

        #region Properties

        /// <summary>Gets or sets the AuditType field. </summary>
        public virtual System.String AuditType
        {
            get { return _auditType; }
            set { _auditType = value; }
        }

        /// <summary>Gets or sets the EMSRecAuditId field. </summary>
        public virtual System.String EMSRecAuditId
        {
            get { return _eMSRecAuditId; }
            set { _eMSRecAuditId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Enforcement.EMSRecAudit.EMSReceipts - Enforcement.EMSReceipts.EMSRecAudits (m:1)'</summary>
        public virtual EMSReceipt EMSReceipt
        {
            get { return _eMSReceipt; }
            set { _eMSReceipt = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the Remarks field. </summary>
        public virtual System.String Remarks
        {
            get { return _remarks; }
            set { _remarks = value; }
        }

        /// <summary>Gets or sets the ReprintType field. </summary>
        public virtual System.String ReprintType
        {
            get { return _reprintType; }
            set { _reprintType = value; }
        }

        /// <summary>Gets or sets the VoidReason field. </summary>
        public virtual System.String VoidReason
        {
            get { return _voidReason; }
            set { _voidReason = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            EMSRecAudit toCompareWith = obj as EMSRecAudit;
            return toCompareWith == null ? false : ((this.EMSRecAuditId == toCompareWith.EMSRecAuditId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.EMSRecAuditId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}