#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Common.GroundInfo'</summary>
    public partial class InterfaceNBSReport : ICommon
    {
        #region Properties

        /// <summary>
        /// Gets or sets the GroundInfoId field.
        /// </summary>
        /// <value>The ground info id.</value>
        public virtual String FileNumber
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Level field.
        /// </summary>
        /// <value>The level.</value>
        public virtual DateTime Date
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the RequestedGrounds field.
        /// </summary>
        /// <value>The requested grounds.</value>
        public virtual String FileNameLocation
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the SubLevel field.
        /// </summary>
        /// <value>The sub level.</value>
        public virtual string FileType
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the GroundInfoId field.
        /// </summary>
        /// <value>The ground info id.</value>
        public virtual String ReportType
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Level field.
        /// </summary>
        /// <value>The level.</value>
        public virtual string LastmodifiedBy
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the RequestedGrounds field.
        /// </summary>
        /// <value>The requested grounds.</value>
        public virtual DateTime LastModifiedDate
        {
            get;
            set;
        }


        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            InterfaceNBSReport toCompareWith = obj as InterfaceNBSReport;
            return toCompareWith == null ? false : ((this.FileNumber == toCompareWith.FileNumber));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.FileNumber.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}