#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MChecklist'</summary>
    public partial class MChecklist : IMaster
    {
        #region Fields

        private System.String _caseType;
        private System.Int64 _checkListId;
        private System.Collections.Generic.ICollection<CheckListInstance> _checkListInstances;
        private System.String _description;
        private Nullable<System.DateTime> _effectiveFromDate;
        private Nullable<System.DateTime> _effectiveToDate;
        private System.String _lastModifiedBy;
        private Nullable<System.DateTime> _lastModifiedDate;
        private System.Collections.Generic.ICollection<MChecklistDocument> _mCheckListDocuments;
        private System.String _name;
        private System.String _notes;
        private System.String _obsInd;
        private System.String _stageDescription;
        private Nullable<System.Int32> _totalStages;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MChecklist"/> class.</summary>
        public MChecklist()
            : base()
        {
            _checkListInstances = new System.Collections.Generic.HashSet<CheckListInstance>();
            _mCheckListDocuments = new System.Collections.Generic.HashSet<MChecklistDocument>();
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CaseType field. </summary>
        public virtual System.String CaseType
        {
            get { return _caseType; }
            set { _caseType = value; }
        }

        /// <summary>Gets or sets the CheckListId field. </summary>
        public virtual System.Int64 CheckListId
        {
            get { return _checkListId; }
            set { _checkListId = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Common.CheckListInstance.MChecklist - Master.MChecklist.CheckListInstances (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<CheckListInstance> CheckListInstances
        {
            get { return _checkListInstances; }
            set { _checkListInstances = value; }
        }

        /// <summary>Gets or sets the Description field. </summary>
        public virtual System.String Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>Gets or sets the EffectiveFromDate field. </summary>
        public virtual Nullable<System.DateTime> EffectiveFromDate
        {
            get { return _effectiveFromDate; }
            set { _effectiveFromDate = value; }
        }

        /// <summary>Gets or sets the EffectiveToDate field. </summary>
        public virtual Nullable<System.DateTime> EffectiveToDate
        {
            get { return _effectiveToDate; }
            set { _effectiveToDate = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual Nullable<System.DateTime> LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MChecklistDocument.MCheckList - Master.MChecklist.MCheckListDocuments (m:1)'</summary>
        public virtual System.Collections.Generic.ICollection<MChecklistDocument> MCheckListDocuments
        {
            get { return _mCheckListDocuments; }
            set { _mCheckListDocuments = value; }
        }

        /// <summary>Gets or sets the Name field. </summary>
        public virtual System.String Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>Gets or sets the Notes field. </summary>
        public virtual System.String Notes
        {
            get { return _notes; }
            set { _notes = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the StageDescription field. </summary>
        public virtual System.String StageDescription
        {
            get { return _stageDescription; }
            set { _stageDescription = value; }
        }

        /// <summary>Gets or sets the TotalStages field. </summary>
        public virtual Nullable<System.Int32> TotalStages
        {
            get { return _totalStages; }
            set { _totalStages = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MChecklist toCompareWith = obj as MChecklist;
            return toCompareWith == null ? false : ((this.CheckListId == toCompareWith.CheckListId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.CheckListId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}