#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.MNAAAlertEventsTemplate'</summary>
    public partial class MNAAAlertEventsTemplate : IMaster
    {
        #region Fields

        private System.Int32 _alertEventTemplateId;
        private System.String _bEInboxLocation;
        private System.String _bETaskItemMessage;
        private System.String _emailMessage;
        private System.String _emailSubject;
        private System.String _fAXMessage;
        private System.String _fETaskItemMessage;
        private System.String _isGroupAllowed;
        private System.String _lastModifiedBy;
        private Nullable<System.DateTime> _lastModifiedDate;
        private MCaseType _mCaseType;
        private MCourtType _mCourtType;
        private MNAASubCategory _mNAASubCategory;
        private System.String _obsInd;
        private System.String _rubberBandInd;
        private System.String _sMSMessage;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="MNAAAlertEventsTemplate"/> class.</summary>
        public MNAAAlertEventsTemplate()
            : base()
        {
            _alertEventTemplateId = default(System.Int32);
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets the AlertEventTemplateId field. </summary>
        public virtual System.Int32 AlertEventTemplateId
        {
            get { return _alertEventTemplateId; }
            set { _alertEventTemplateId = value; }
        }

        /// <summary>Gets or sets the BEInboxLocation field. </summary>
        public virtual System.String BEInboxLocation
        {
            get { return _bEInboxLocation; }
            set { _bEInboxLocation = value; }
        }

        /// <summary>Gets or sets the BETaskItemMessage field. </summary>
        public virtual System.String BETaskItemMessage
        {
            get { return _bETaskItemMessage; }
            set { _bETaskItemMessage = value; }
        }

        /// <summary>Gets or sets the EmailMessage field. </summary>
        public virtual System.String EmailMessage
        {
            get { return _emailMessage; }
            set { _emailMessage = value; }
        }

        /// <summary>Gets or sets the EmailSubject field. </summary>
        public virtual System.String EmailSubject
        {
            get { return _emailSubject; }
            set { _emailSubject = value; }
        }

        /// <summary>Gets or sets the FAXMessage field. </summary>
        public virtual System.String FAXMessage
        {
            get { return _fAXMessage; }
            set { _fAXMessage = value; }
        }

        /// <summary>Gets or sets the FETaskItemMessage field. </summary>
        public virtual System.String FETaskItemMessage
        {
            get { return _fETaskItemMessage; }
            set { _fETaskItemMessage = value; }
        }

        /// <summary>Gets or sets the IsGroupAllowed field. </summary>
        public virtual System.String IsGroupAllowed
        {
            get { return _isGroupAllowed; }
            set { _isGroupAllowed = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual Nullable<System.DateTime> LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MNAAAlertEventsTemplate.MCaseType - Master.MCaseType.MNAAAlertEventsTemplates (m:1)'</summary>
        public virtual MCaseType MCaseType
        {
            get { return _mCaseType; }
            set { _mCaseType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MNAAAlertEventsTemplate.MCourtType - Master.MCourtType.MNAAAlertEventsTemplates (m:1)'</summary>
        public virtual MCourtType MCourtType
        {
            get { return _mCourtType; }
            set { _mCourtType = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Master.MNAAAlertEventsTemplate.MNAASubCategory - Master.MNAASubCategory.MNAAAlertEventsTemplates (m:1)'</summary>
        public virtual MNAASubCategory MNAASubCategory
        {
            get { return _mNAASubCategory; }
            set { _mNAASubCategory = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the RubberBandInd field. </summary>
        public virtual System.String RubberBandInd
        {
            get { return _rubberBandInd; }
            set { _rubberBandInd = value; }
        }

        /// <summary>Gets or sets the SMSMessage field. </summary>
        public virtual System.String SMSMessage
        {
            get { return _sMSMessage; }
            set { _sMSMessage = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            MNAAAlertEventsTemplate toCompareWith = obj as MNAAAlertEventsTemplate;
            return toCompareWith == null ? false : ((this.AlertEventTemplateId == toCompareWith.AlertEventTemplateId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.AlertEventTemplateId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}