#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'PrintDocumentQueueDetail'</summary>
    public partial class PrintDocumentQueueDetail : ICommon
    {
        #region Fields

        private System.String _printDocumentQueueId;
        private System.String _printDocumentQueueDetailID;
        private System.String _docId;
        private System.Int32 _sequenceNo;
        private System.String _documentRemarks;
        private System.String _obsInd;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="PrintDocumentQueueDetail"/> class.</summary>
        public PrintDocumentQueueDetail()
            : base()
        {}

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the PrintDocumentQueueId field. </summary>
        public virtual System.String PrintDocumentQueueId
        {
            get { return _printDocumentQueueId; }
            set { _printDocumentQueueId = value; }
        }

        /// <summary>Gets or sets the DocId field. </summary> Add Sequence No tp PRintDocQueueDetail.
        public virtual System.String DocId
        {
            get { return _docId; }
            set { _docId = value; }
        }

        /// <summary>Gets or sets the SequenceNo field. </summary>
        public virtual System.Int32 SequenceNo
        {
            get { return _sequenceNo; }
            set { _sequenceNo = value; }
        }

        /// <summary>Gets or sets the PrintDocumentQueueDetailID field. </summary>
        public virtual System.String PrintDocumentQueueDetailID
        {
            get { return _printDocumentQueueDetailID; }
            set { _printDocumentQueueDetailID = value; }
        }

        /// <summary>Gets or sets the DocumentRemarks field. </summary>
        public virtual System.String DocumentRemarks
        {
            get { return _documentRemarks; }
            set { _documentRemarks = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            PrintDocumentQueueDetail toCompareWith = obj as PrintDocumentQueueDetail;
            return toCompareWith == null ? false : ((this.PrintDocumentQueueId == toCompareWith.PrintDocumentQueueId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.PrintDocumentQueueId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}