#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Case.RCaseLinked'</summary>
    public partial class RCaseLinked : ICase
    {
        #region Fields

        private System.Int64 _caseInfoId;
        private System.String _crossCourtInd;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.DateTime _linkedDate;
        private System.String _linkGroupId;
        private System.String _obsInd;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="RCaseLinked"/> class.</summary>
        public RCaseLinked()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CaseInfoId field. </summary>
        public virtual System.Int64 CaseInfoId
        {
            get { return _caseInfoId; }
            set { _caseInfoId = value; }
        }

        /// <summary>Gets or sets the CrossCourtInd field. </summary>
        public virtual System.String CrossCourtInd
        {
            get { return _crossCourtInd; }
            set { _crossCourtInd = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the LinkedDate field. </summary>
        public virtual System.DateTime LinkedDate
        {
            get { return _linkedDate; }
            set { _linkedDate = value; }
        }

        /// <summary>Gets or sets the LinkGroupId field. </summary>
        public virtual System.String LinkGroupId
        {
            get { return _linkGroupId; }
            set { _linkGroupId = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            RCaseLinked toCompareWith = obj as RCaseLinked;
            return toCompareWith == null ? false : ((this.LinkGroupId == toCompareWith.LinkGroupId) && (this.CaseInfoId == toCompareWith.CaseInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.LinkGroupId.GetHashCode();
            toReturn ^= this.CaseInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}