#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'BackEndSpecific.ReportConfigUser'</summary>
    public partial class ReportConfigUser : IBackEndSpecific
    {
        #region Fields

        //private JudicialUser _judicialUser;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _obsInd;
        private System.String _reportConfigInfoId;

        //private ReportConfigInfo _reportConfigInfo;
        private System.String _reportConfigUserId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="ReportConfigUser"/> class.</summary>
        public ReportConfigUser()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'BackEndSpecific.ReportConfigUser.JudicialUser - BackEndSpecific.JudicialUser.ReportConfigUsers (m:1)'</summary>
        //public virtual JudicialUser JudicialUser
        //{
        //    get { return _judicialUser; }
        //    set { _judicialUser = value; }
        //}
        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Represents the navigator which is mapped onto the association 'BackEndSpecific.ReportConfigUser.ReportConfigInfo - BackEndSpecific.ReportConfigInfo.ReportConfigUsers (m:1)'</summary>
        //public virtual ReportConfigInfo ReportConfigInfo
        //{
        //    get { return _reportConfigInfo; }
        //    set { _reportConfigInfo = value; }
        //}
        /// <summary>Gets or sets the ReportConfigInfoId field. </summary>
        public virtual System.String ReportConfigInfoId
        {
            get { return _reportConfigInfoId; }
            set { _reportConfigInfoId = value; }
        }

        /// <summary>Gets or sets the ReportConfigUserId field. </summary>
        public virtual System.String ReportConfigUserId
        {
            get { return _reportConfigUserId; }
            set { _reportConfigUserId = value; }
        }

        /// <summary>Gets or sets the UserId field. </summary>
        public virtual System.String UserId
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            ReportConfigUser toCompareWith = obj as ReportConfigUser;
            return toCompareWith == null ? false : ((this.ReportConfigUserId == toCompareWith.ReportConfigUserId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.ReportConfigUserId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}