#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;

    /// <summary>Class which represents the entity 'Master.RMHrgSlotLegis'</summary>
    [Serializable]
    public partial class RMHrgSlotLegis : IMaster
    {

        /// <summary>Initializes a new instance of the <see cref="RMHrgSlotLegis"/> class.</summary>
        public RMHrgSlotLegis()
            : base()
        {

        }

        #region Properties

        public virtual string RMHrgSlotLegisId { get; set; }
        public virtual string ForumID { get; set; }
        public virtual string HrgSlotCode { get; set; }
        public virtual string ActCode { get; set; }
        public virtual string ProvisionCode { get; set; }
        public virtual string ProvisionNo { get; set; }
        public virtual string ObsInd { get; set; }
        public virtual string LastModifiedBy { get; set; }
        public virtual DateTime LastModifiedDate { get; set; }
        public virtual string HRGTypeCode { get; set; }
        public virtual string SectionCode { get; set; }
        public virtual string CaseType { get; set; }
        public virtual Nullable<DateTime> LastSectionAssignedDate { get; set; }
        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
            RMHrgSlotLegis toCompareWith = obj as RMHrgSlotLegis;
            return toCompareWith == null ? false : ((this.RMHrgSlotLegisId == toCompareWith.RMHrgSlotLegisId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.RMHrgSlotLegisId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}