#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Master.RMHRGOutComePartyStatus'</summary>
    public partial class RMHRGOutComePartyStatus : IMaster
    {
        #region Fields

        private System.String _caseTypeCode;
        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private MCaseStatus _mCaseStatus;
        private MCaseTypeGroup _mCaseTypeGroup;
        private MHRGOutCome _mHRGOutCome;
        private MPartyStatus _mPartyStatus;
        private System.String _nOACode;
        private System.String _obsInd;
        private System.String _rMHrgOutComePartyStatusId;
        private System.String _subCaseTypeCode;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="RMHRGOutComePartyStatus"/> class.</summary>
        public RMHRGOutComePartyStatus()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Gets or sets the CaseTypeCode field. </summary>
        public virtual System.String CaseTypeCode
        {
            get { return _caseTypeCode; }
            set { _caseTypeCode = value; }
        }

        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the MCaseStatus field. </summary>
        public virtual MCaseStatus MCaseStatus
        {
            get { return _mCaseStatus; }
            set { _mCaseStatus = value; }
        }

        /// <summary>Gets or sets the MCaseTypeGroup field. </summary>
        public virtual MCaseTypeGroup MCaseTypeGroup
        {
            get { return _mCaseTypeGroup; }
            set { _mCaseTypeGroup = value; }
        }

        /// <summary>Gets or sets the MHRGOutCome field. </summary>
        public virtual MHRGOutCome MHRGOutCome
        {
            get { return _mHRGOutCome; }
            set { _mHRGOutCome = value; }
        }

        /// <summary>Gets or sets the MPartyStatus field. </summary>
        public virtual MPartyStatus MPartyStatus
        {
            get { return _mPartyStatus; }
            set { _mPartyStatus = value; }
        }

        /// <summary>Gets or sets the NOACode field. </summary>
        public virtual System.String NOACode
        {
            get { return _nOACode; }
            set { _nOACode = value; }
        }

        /// <summary>Gets or sets the ObsInd field. </summary>
        public virtual System.String ObsInd
        {
            get { return _obsInd; }
            set { _obsInd = value; }
        }

        /// <summary>Gets or sets the RMHrgOutComePartyStatusId field. </summary>
        public virtual System.String RMHrgOutComePartyStatusId
        {
            get { return _rMHrgOutComePartyStatusId; }
            set { _rMHrgOutComePartyStatusId = value; }
        }

        /// <summary>Gets or sets the SubCaseTypeCode field. </summary>
        public virtual System.String SubCaseTypeCode
        {
            get { return _subCaseTypeCode; }
            set { _subCaseTypeCode = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            RMHRGOutComePartyStatus toCompareWith = obj as RMHRGOutComePartyStatus;
            return toCompareWith == null ? false : (this.RMHrgOutComePartyStatusId == toCompareWith.RMHrgOutComePartyStatusId);
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.RMHrgOutComePartyStatusId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}