#region Header

//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.0.</auto-generated>
//------------------------------------------------------------------------------

#endregion Header

namespace AllInOne.Legal.Entities.BackEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    /// <summary>Class which represents the entity 'Subsequent.SubpoenaInfo'</summary>
    public partial class SubpoenaInfo : ISubsequent
    {
        #region Fields

        private System.String _lastModifiedBy;
        private System.DateTime _lastModifiedDate;
        private System.String _modeOfAttendance;
        private System.String _purposeOfSubpoena;
        private System.String _submissionGroupId;
        private System.String _subpoenaInfoId;

        #endregion Fields

        #region Constructors

        /// <summary>Initializes a new instance of the <see cref="SubpoenaInfo"/> class.</summary>
        public SubpoenaInfo()
            : base()
        {
        }

        #endregion Constructors

        #region Properties

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.SubpoenaInfo.Hearing - Case.Hearing.SubpoenaInfos (m:1)'</summary>
        public virtual Nullable<Int64> HrgId
        {
            get;
            set;
        }

        /// <summary>Represents the navigator which is mapped onto the association 'Subsequent.SubpoenaInfo.Hearing - Case.Hearing.SubpoenaInfos (m:1)'</summary>
        //public virtual Hearing Hearing
        //{
        //    get { return _hearing; }
        //    set { _hearing = value; }
        //}
        /// <summary>Gets or sets the LastModifiedBy field. </summary>
        public virtual System.String LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set { _lastModifiedBy = value; }
        }

        /// <summary>Gets or sets the LastModifiedDate field. </summary>
        public virtual System.DateTime LastModifiedDate
        {
            get { return _lastModifiedDate; }
            set { _lastModifiedDate = value; }
        }

        /// <summary>Gets or sets the ModeOfAttendance field. </summary>
        public virtual System.String ModeOfAttendance
        {
            get { return _modeOfAttendance; }
            set { _modeOfAttendance = value; }
        }

        /// <summary>Gets or sets the PurposeOfSubpoena field. </summary>
        public virtual System.String PurposeOfSubpoena
        {
            get { return _purposeOfSubpoena; }
            set { _purposeOfSubpoena = value; }
        }

        /// <summary>Gets or sets the SubmissionGroupId field. </summary>
        public virtual System.String SubmissionGroupId
        {
            get { return _submissionGroupId; }
            set { _submissionGroupId = value; }
        }

        /// <summary>Gets or sets the SubpoenaInfoId field. </summary>
        public virtual System.String SubpoenaInfoId
        {
            get { return _subpoenaInfoId; }
            set { _subpoenaInfoId = value; }
        }

        #endregion Properties

        #region Methods

        /// <summary>Determines whether the specified object is equal to this instance.</summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns><c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.</returns>
        public override bool Equals(object obj)
        {
            if(obj == null)
            {
                return false;
            }
            SubpoenaInfo toCompareWith = obj as SubpoenaInfo;
            return toCompareWith == null ? false : ((this.SubpoenaInfoId == toCompareWith.SubpoenaInfoId));
        }

        /// <summary>Returns a hash code for this instance.</summary>
        /// <returns>A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. </returns>
        public override int GetHashCode()
        {
            int toReturn = base.GetHashCode();
            toReturn ^= this.SubpoenaInfoId.GetHashCode();
            return toReturn;
        }

        #endregion Methods
    }
}